.TH mputstr 1 "April 1993" "Scilab Group" "Scilab Function"
.so ../sci.an
.SH NAME
mputstr - write a character string in a file
.SH CALLING SEQUENCE
.nf
err=mputstr(str [, fd]); 
.fi
.SH PARAMETERS
.TP 10
fd
: scalar. The \fVfd\fR parameter returned by the function
\fVmopen\fR. -1 stands for last opened file. Default value is -1.
.TP 
str
: a character string
.TP
err
: scalar. Error indicator

.SH DESCRIPTION
mputstr function allows to write a character string  in a binary file.
.SH SEE ALSO
mclose, meof, mfprintf, fprintfMat, mfscanf, fscanfMat, mget, mgetstr, mopen, mprintf, mput, mputstr, mscanf, mseek, mtell


