.TH mtell 1 "April 1999" "Scilab Group" "Scilab Function"
.so ../sci.an
.SH NAME
mtell - binary file management
.SH CALLING SEQUENCE
.nf
mtell([fd])	
.fi
.SH PARAMETERS
.TP 10
fd
: scalar. The \fVfd\fR parameter returned by the function
\fVmopen\fR. -1 stands for last opened file. Default value is -1.
.SH DESCRIPTION
The function \fVmtell()\fR returns the offset of the current byte  relative  to
the beginning of the file associated with the named stream \fVfd\fR.
.SH SEE ALSO
mclose, meof, mfprintf, fprintfMat, mfscanf, fscanfMat, mget, mgetstr, mopen, mprintf, mput, mputstr, mscanf, mseek, mtell


