.TH scicos_block  "Janvier 1997" "Scilab Group" "Scicos data structure"
.so ../sci.an
.SH NAME
scicos_block - Scicos block data structure
.SH DEFINITION
.nf
blk=list('Block',graphics,model,void,gui)
.fi
.SH PARAMETERS
.TP
'Block'
: keyword used to define list as a Scicos block representation
.TP
graphics
: Scilab list, graphic properties data structure
.TP
model
: Scilab list, system properties data structure
.TP
void
: unused, reserved for future use.
.TP
gui
: character string, the name of the graphic user interface function
(generally written in Scilab) associated with the block.
.TP
blk
: Scilab list, Scicos block data structure
.SH DESCRIPTION
Scicos editor creates and uses for each block a data structure
containing all information relative to the graphic interface and
simulation part of the block.
.SH SEE ALSO
scicos, scicos_graphic, scicos_model







