.TH plot2d3 2 "April 1993" "Scilab Group" "Scilab Function"
.so ../sci.an
.SH NAME
plot2d3 - multiple plot of functions (vertical bars)
.SH CALLING SEQUENCE
.nf
plot2d3(str,x,y,[style,strf,leg,rect,nax])
.fi
.SH PARAMETERS
see \fVplot2d\fR and \fVplot2d1\fR
.SH DESCRIPTION
Same as \fVplot2d1\fR but curves are plotted using vertical bars.

Enter the command \fVplot2d3()\fR to see a demo.
.SH SEE ALSO
plot2d, plot2d1, plot2d2, plot2d4
.SH AUTHOR
J.Ph.C..




