.TH plzr 1 "April 1993" "Scilab Group" "Scilab Function"
.so ../sci.an
.SH NAME
plzr - pole-zero plot
.SH CALLING SEQUENCE
.nf
plzr(sl) 
.fi
.SH PARAMETERS
.TP 10
sl
: list ( \fVsyslin\fR)
.SH DESCRIPTION
produces a pole-zero plot of the linear system
\fVsl\fR (\fVsyslin\fR list)
.SH EXAMPLE
.nf 
s=poly(0,'s');
n=[1+s   2+3*s+4*s^2        5; 0        1-s             s];
d=[1+3*s   5-s^3           s+1;1+s     1+s+s^2      3*s-1];
h=syslin('c',n./d); 
plzr(h);
.fi
.SH SEE ALSO
trzeros, roots, syslin

