.TH xclea 2 "April 1993" "Scilab Group" "Scilab Function"
.so ../sci.an
.SH NAME
xclea - erase a rectangle on a graphic window
.SH CALLING SEQUENCE
.nf
xclea(x,y,w,h)
.fi
.SH PARAMETERS 
.TP 15
x,y,w,h 
: four real values (rectangle def)
.SH DESCRIPTION
clears on the current graphic window the rectangle \fV[x,y,w,h]\fR
( Upper left point , width,height) using the current graphic scale.
.SH AUTHOR
J.Ph.C.



