.TH zeropen 1 "April 1993" "Scilab Group" "Scilab Function"
.so ../sci.an
.SH NAME
zeropen - zero pencil
.SH CALLING SEQUENCE
.nf
[Z,U]=zeropen(Sl)
.fi
.SH PARAMETERS
.TP
Sl
: a linear system (\fVsyslin\fR list in state-space form \fV[A,B,C,D]\fR)
.TP
Z
: matrix pencil \fVZ=s*E-A\fR
.TP
U
: square orthogonal matrix
.SH DESCRIPTION
\fVZ = sE - F\fR  is the zero pencil of the linear system \fVSl\fR with 
matrices \fV[A,B,C,D]\fR. Utility function.
.LP
With \fVU\fR row compression of \fV[B;D]\fR i.e, \fVU*[B;D]=[0;*]\fR; one has:
.nf
U*[-sI+A |B;   [ Z |0;      
      C  |D] = [ * |*]
.fi
The zeros of \fVZ\fR are the zeros of \fVSl\fR.
.SH SEE ALSO
systmat, kroneck



