# LaTeX2HTML 96.1 (Feb 5, 1996)
# Associate images original text with physical files.

$key = q/{_inline}$K=YQ^-1${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=79 HEIGHT=26 ALIGN=MIDDLE ALT="tex2html_wrap_inline662" SRC="img19.gif"  > '; 
$key = q/{_inline}$Y(1),ldots,Y(N)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=109 HEIGHT=23 ALIGN=MIDDLE ALT="tex2html_wrap_inline706" SRC="img26.gif"  > '; 
$key = q/{displaymath}arrayllmboxminimize;SPMamp;tildec^Tzmboxsubjectto;SPMamp;tildeF_0+z_1tildeF_1+cdots+z_tildemtildeF_tildemgeq0,;;Az+b=0,array{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=445 HEIGHT=38 ALIGN=BOTTOM ALT="displaymath886" SRC="img63.gif"  > '; 
$key = q/{_inline}$Pi=(pi_ij)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=67 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline682" SRC="img22.gif"  > '; 
$key = q/{_inline}$|u(t)|${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=41 HEIGHT=23 ALIGN=MIDDLE ALT="tex2html_wrap_inline648" SRC="img14.gif"  > '; 
$key = q/{displaymath}dotx=Ax+Bu{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=297 HEIGHT=13 ALIGN=BOTTOM ALT="displaymath630" SRC="img10.gif"  > '; 
$key = q/{_inline}${1,ldots,N}${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=74 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline678" SRC="img21.gif"  > '; 
$key = q/{displaymath}AXB=C{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=287 HEIGHT=11 ALIGN=BOTTOM ALT="displaymath833" SRC="img51.gif"  > '; 
$key = q/{displaymath}z=Nx+z_0,{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=297 HEIGHT=14 ALIGN=BOTTOM ALT="displaymath887" SRC="img65.gif"  > '; 
$key = q/{displaymath}Sigma:;;left{arrayllmboxminimize;SPMamp;f(X_1,ldots,X_M)mboxsubjectto;SPMamp;left{arraylG_i(X_1,ldots,X_M)=0,;;i=1,2,...,p,H_j(X_1,ldots,X_M)geq0,;;j=1,2,..,q.arrayright.arrayright.{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=462 HEIGHT=58 ALIGN=BOTTOM ALT="displaymath570" SRC="img2.gif"  > '; 
$key = q/{_inline}$K(i)=Y(i)Q(i)^-1${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=134 HEIGHT=25 ALIGN=MIDDLE ALT="tex2html_wrap_inline708" SRC="img29.gif"  > '; 
$key = q/{_inline}$geq${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=10 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline820" SRC="img49.gif"  > '; 
$key = q/{_inline}$A(1),ldots,A(N)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=108 HEIGHT=23 ALIGN=MIDDLE ALT="tex2html_wrap_inline712" SRC="img31.gif"  > '; 
$key = q/{_inline}$tgeq0${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=35 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline650" SRC="img15.gif"  > '; 
$key = q/{_inline}$N,z_0${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=35 HEIGHT=22 ALIGN=MIDDLE ALT="tex2html_wrap_inline904" SRC="img66.gif"  > '; 
$key = q/{_inline}$|x(0)|leq1${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=75 HEIGHT=23 ALIGN=MIDDLE ALT="tex2html_wrap_inline646" SRC="img13.gif"  > '; 
$key = q/{displaymath}X-X^T=0,;;Y-Y^T=0,{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=349 HEIGHT=18 ALIGN=BOTTOM ALT="displaymath750" SRC="img42.gif"  > '; 
$key = q/{displaymath}P=-left(arrayccc0;SPMamp;0;SPMamp;Iarrayright)left(arraycccAPA^T+Q;SPMamp;0;SPMamp;E0;SPMamp;R;SPMamp;CE^T;SPMamp;C^T;SPMamp;0arrayright)^-1left(arrayc00Iarrayright).{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=460 HEIGHT=61 ALIGN=BOTTOM ALT="displaymath778" SRC="img45.gif"  > '; 
$key = q/{_inline}$F_0,ldots,F_m${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=76 HEIGHT=22 ALIGN=MIDDLE ALT="tex2html_wrap_inline908" SRC="img68.gif"  > '; 
$key = q/{displaymath}P-P^T=0{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=292 HEIGHT=15 ALIGN=BOTTOM ALT="displaymath779" SRC="img46.gif"  > '; 
$key = q/{displaymath}arrayllmboxminimize;SPMamp;c^Txmboxsubjectto;SPMamp;F_0+x_1F_1+cdots+x_mF_mgeq0,array{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=399 HEIGHT=37 ALIGN=BOTTOM ALT="displaymath888" SRC="img67.gif"  > '; 
$key = q/{_inline}$K=LX^-1${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=79 HEIGHT=13 ALIGN=BOTTOM ALT="tex2html_wrap_inline770" SRC="img41.gif"  > '; 
$key = q/{_inline}$z_0${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=14 HEIGHT=14 ALIGN=MIDDLE ALT="tex2html_wrap_inline898" SRC="img64.gif"  > '; 
$key = q/{displaymath}Q-Q^T=0{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=292 HEIGHT=18 ALIGN=BOTTOM ALT="displaymath631" SRC="img17.gif"  > '; 
$key = q/{displaymath}left(arraycccAPA^T+Q;SPMamp;0;SPMamp;EP0;SPMamp;R;SPMamp;CPP^TE^T;SPMamp;P^TC^T;SPMamp;Parrayright)geq0.{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=380 HEIGHT=59 ALIGN=BOTTOM ALT="displaymath780" SRC="img47.gif"  > '; 
$key = q/{_inline}$z_1${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=13 HEIGHT=14 ALIGN=MIDDLE ALT="tex2html_wrap_inline766" SRC="img39.gif"  > '; 
$key = q/{_inline}$X_1,ldots,X_M${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=85 HEIGHT=22 ALIGN=MIDDLE ALT="tex2html_wrap_inline572" SRC="img3.gif"  > '; 
$key = q/{_inline}$z_2${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=13 HEIGHT=14 ALIGN=MIDDLE ALT="tex2html_wrap_inline768" SRC="img40.gif"  > '; 
$key = q/{_inline}$mboxE(|x-hatx|^2)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=85 HEIGHT=25 ALIGN=MIDDLE ALT="tex2html_wrap_inline870" SRC="img55.gif"  > '; 
$key = q/{_inline}$F_i${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=14 HEIGHT=22 ALIGN=MIDDLE ALT="tex2html_wrap_inline914" SRC="img69.gif"  > '; 
$key = q/{_inline}$G_i${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=16 HEIGHT=22 ALIGN=MIDDLE ALT="tex2html_wrap_inline578" SRC="img4.gif"  > '; 
$key = q/{displaymath}dotx=A(r(t))x+B(r(t))u,{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=338 HEIGHT=15 ALIGN=BOTTOM ALT="displaymath666" SRC="img20.gif"  > '; 
$key = q/{_inline}$H_j${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=19 HEIGHT=22 ALIGN=MIDDLE ALT="tex2html_wrap_inline582" SRC="img5.gif"  > '; 
$key = q/{_inline}$Sigma${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=9 HEIGHT=11 ALIGN=BOTTOM ALT="tex2html_wrap_inline590" SRC="img7.gif"  > '; 
$key = q/{_inline}$ntimesn_u${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=47 HEIGHT=18 ALIGN=MIDDLE ALT="tex2html_wrap_inline640" SRC="img12.gif"  > '; 
$key = q/{_inline}$n_utimesn${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=46 HEIGHT=18 ALIGN=MIDDLE ALT="tex2html_wrap_inline656" SRC="img16.gif"  > '; 
$key = q/{displaymath}hatx=Ly{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=275 HEIGHT=15 ALIGN=BOTTOM ALT="displaymath852" SRC="img54.gif"  > '; 
$key = q/{_inline}$|T_z_1w|_infty${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=60 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline760" SRC="img38.gif"  > '; 
$key = q/{figure}[hb]centerlinepsfigfigure=fig4.eps,height=12cm{figure}/;
$cached_env_img{$key} = ' <IMG WIDTH=408 HEIGHT=566 ALIGN=BOTTOM ALT="figure254" SRC="img61.gif"  > '; 
$key = q/{_inline}$Pi${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=11 HEIGHT=11 ALIGN=BOTTOM ALT="tex2html_wrap_inline716" SRC="img33.gif"  > '; 
$key = q/{displaymath}AX+XB=C{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=305 HEIGHT=12 ALIGN=BOTTOM ALT="displaymath832" SRC="img50.gif"  > '; 
$key = q/{figure}[ht]centerlinepsfigfigure=fig3.eps,height=6cm{figure}/;
$cached_env_img{$key} = ' <IMG WIDTH=450 HEIGHT=283 ALIGN=BOTTOM ALT="figure250" SRC="img60.gif"  > '; 
$key = q/{_inline}$lim_trightarrowinftymboxbfE|x(t)|^2=0${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=152 HEIGHT=25 ALIGN=MIDDLE ALT="tex2html_wrap_inline692" SRC="img24.gif"  > '; 
$key = q/{_inline}$|T_z_2w|_2${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=54 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline758" SRC="img37.gif"  > '; 
$key = q/{_inline}$|T_z_1w|_infty;SPMlt;gamma${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=93 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline756" SRC="img36.gif"  > '; 
$key = q/{_inline}$ntimesn${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=38 HEIGHT=16 ALIGN=MIDDLE ALT="tex2html_wrap_inline636" SRC="img11.gif"  > '; 
$key = q/{figure}[hb]centerlinepsfigfigure=fig2.eps,height=6cmlabelf1{figure}/;
$cached_env_img{$key} = ' <IMG WIDTH=450 HEIGHT=283 ALIGN=BOTTOM ALT="figure245" SRC="img59.gif"  > '; 
$key = q/{displaymath}arrayccmboxminimize;SPMamp;e^Txmboxsubjectto;SPMamp;Ax+bgeq0,;SPMamp;Cx+d=0.array{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=336 HEIGHT=55 ALIGN=BOTTOM ALT="displaymath808" SRC="img48.gif"  > '; 
$key = q/{_inline}$X_i${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=18 HEIGHT=22 ALIGN=MIDDLE ALT="tex2html_wrap_inline610" SRC="img8.gif"  > '; 
$key = q/{_inline}$Q(1),ldots,Q(N)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=109 HEIGHT=23 ALIGN=MIDDLE ALT="tex2html_wrap_inline702" SRC="img25.gif"  > '; 
$key = q/{_inline}$B(1),ldots,B(N)${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=112 HEIGHT=23 ALIGN=MIDDLE ALT="tex2html_wrap_inline714" SRC="img32.gif"  > '; 
$key = q/{_inline}$gamma${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=8 HEIGHT=14 ALIGN=MIDDLE ALT="tex2html_wrap_inline874" SRC="img56.gif"  > '; 
$key = q/{_inline}$Vgeq0${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=41 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline586" SRC="img6.gif"  > '; 
$key = q/{_inline}$i=1,ldots,N${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=87 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline710" SRC="img30.gif"  > '; 
$key = q/{_inline}$5times1${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=34 HEIGHT=20 ALIGN=MIDDLE ALT="tex2html_wrap_inline626" SRC="img9.gif"  > '; 
$key = q/{displaymath}HinmboxbfColeft{H(1),...,H(N)right},;;;VinmboxbfColeft{V(1),...,V(N)right}{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=443 HEIGHT=16 ALIGN=BOTTOM ALT="displaymath851" SRC="img53.gif"  > '; 
$key = q/{displaymath}y=Hx+Vw{displaymath}/;
$cached_env_img{$key} = ' <IMG WIDTH=299 HEIGHT=14 ALIGN=BOTTOM ALT="displaymath850" SRC="img52.gif"  > '; 
$key = q/{_inline}$H_2H_infty${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=54 HEIGHT=24 ALIGN=MIDDLE ALT="tex2html_wrap_inline568" SRC="img1.gif"  > '; 
$key = q/{figure}[hbtp]centerlinepsfigfigure=fig8.eps,height=15cmvskip.5cmcenterlinepsfigfigure=fig6.eps,height=3cm{figure}/;
$cached_env_img{$key} = ' <IMG WIDTH=464 HEIGHT=876 ALIGN=BOTTOM ALT="figure258" SRC="img62.gif"  > '; 
$key = q/{_inline}$pi_ij${_inline}/;
$cached_env_img{$key} = ' <IMG WIDTH=20 HEIGHT=14 ALIGN=MIDDLE ALT="tex2html_wrap_inline684" SRC="img23.gif"  > '; 

1;

