.TH cmb_lin 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
cmb_lin - symbolic linear combination
.SH CALLING SEQUENCE
.nf
[x]=cmb_lin(alfa,x,beta,y)
.fi
.SH DESCRIPTION
Evaluates \fValfa*x-beta*y\fR. \fV alfa, beta, x, y\fR are character
strings.
(low-level routine)
.SH SEE ALSO
mulf, addf
