.TH minicf 1 "October 1994" "Scilab Group" "Scilab macro"
.so man1/sci.an
.SH NAME 
minicf - minimum linear cost for imposed flow  
.SH CALLING SEQUENCE
.nf
[c,f,v] = minicf(iv,[g])
.fi
.SH PARAMETERS
.TP 3
iv
: integer, imposed value for the flow
.TP 2
g
: graph list, optional argument with default value \fVthe_g\fR
.TP 2
c
: integer, cost value of the flow on the return arc (sink, source)
.TP 2
f
: array of the flows on the arcs
.TP 2
v
: value of the return flow
.SH DESCRIPTION
\fVmincf0\fR returns the minimum linear cost for the imposed flow 
\fViv\fR from the source to the sink for the directed graph \fVg\fR 
with only one source and one sink.
\fVf\fR is the array of the flows on the arcs, f is the array of the 
flows on the arcs and v the value of the flow on the return arc.
.SH SEE ALSO
mincfr, mincf0, minqflow
