.TH netwindows 1 "October 1994" "Scilab Group" "Scilab function"
.so man1/sci.an
.SH NAME
netwindows - get Metanet windows numbers
.SH CALLING SEQUENCE
.nf
[windows] = netwindows()
.fi
.SH PARAMETERS
.TP 8
windows
: row vector of Metanet window numbers
.SH DESCRIPTION
This function is used to get a row vector of the all the Metanet window
numbers.
.SH SEE ALSO
metanet, netwindow
