.TH showns 1 "October 1994" "Scilab Group" "Scilab function"
.so man1/sci.an
.SH NAME 
showns - highlight a set of nodes
.SH CALLING SEQUENCE
.nf
showns(ns,[sup])
.fi
.SH PARAMETERS
.TP 3
ns
: row vector of node numbers
.TP 4
sup
: integer, optional variable with default value 0
.SH DESCRIPTION
\fVshowns\fR highlights the set of nodes \fVns\fR of the displayed graph in
the \fVMetanet\fR window. 
If the optional variable (with default value 0) \fVsup\fR is equal to 1,
the highlighting is superposed on the previous one.
.SH SEE ALSO
showp, netwindows
