.TH transclo 1 "October 1994" "Scilab Group" "Scilab Macro"
.so man1/sci.an
.SH NAME 
transclo - transitive closure 
.SH CALLING SEQUENCE
.nf
[g1] = transclo([g])
.fi
.SH PARAMETERS
.TP 2
g
: graph list, optional argument with default value \fVthe_g\fR
.TP 3
g1
: graph list
.SH DESCRIPTION
\fVtransclo\fR returns the graph \fVg1\fR corresponding to 
the transitive closure of graph \fVg\fR.
