.TH jmat 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
jmat - row or column block permutation
.SH CALLING SEQUENCE
.nf
[j]=jmat(n,m)
.fi
.SH PARAMETERS
.TP
n
: number of block rows or block columns of the matrix
.TP
m
: size of the (square) blocks
.SH DESCRIPTION
This function permutes block rows or block columns of a matrix

