.TH armap 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
armap - display of armax equations
.SH CALLING SEQUENCE
.nf
[]=armap(ar,[out])
.fi
.SH PARAMETERS
.TP 
ar 
: a list describing an arma process.
.TP
out 
: a file name 
.SH DESCRIPTION
Display in the file out or on the screen the armax equation associated with \fVar\fR. 
\fVar\fR is created with armac 
.SH SEE ALSO 
armac 

