.TH Bxxx 2 "April 1993" "Scilab Group" "Scilab Function" 
.so man1/sci.an
.SH NAME
Bxxx - printing scilab graphics 
.SH CALLING SEQUENCE
.nf
Blatexpr xscale yscale filename.ps
BEpsf filename.ps 
Blpr "Title" filename1.ps filename2.ps ... filenamen.ps | lpr 
.fi
.SH DESCRIPTION
The scilab graphics can be saved with the \fVxbasimp\fR
command into unix files. The scilab command :
.nf 
	xbasimp(xx,'des.ps',0)
.fi
will save the graphics recorded in the graphic window xx in the 
file \fVdes.ps.xx\fR. This file can't be directly send to a Postscript
printer and a set of programs ( in the \fVbin\fR scilab directory ) are 
given with Scilab to print it :
.TP 10
BEpsf 
: The \fVBEpsf\fR command will create an Epsf file from your \fVdes.ps.xx\fR
under the name \fVdes.epsf\fR, this Epsf file can be printed on a
Postscript printer or inserted into an other Postscript document.
.TP
Blatexpr 
: The  \fVBlatexpr\fR command will create an Epsf file from your
\fVdes.ps.xx\fR under the name \fVdes.epsf\fR and a LaTeX file 
\fVdes.tex\fR. See the Scilab Documentation for further informations
on how to use \fVdes.tex\fR. 
.TP
Blpr 
: The \fVBlpr\fR command is used to print a set of graphics on a same 
sheet of paper. For example to print two graphics on a unique page one
can use :
.nf 
Blpt "Two graphics" file1.ps.0 file2.ps.1 | lpr 
.fi
.SH SEE ALSO
xbasimp

