SOURCES=*.java

JAVAC=javac -d $(HOME)/Cours/Oap/info/classes -classpath $(HOME)/Cours/Oap/info/classes -g 

all:
	$(JAVAC)  $(SOURCES)

clean:
	$(RM) -f $(HOME)/Cours/Oap/info/classes/*.class


