.TH compla 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME 
compl2 - arc array from pointer and node arrays
.SH CALLING SEQUENCE
.nf
[la] = compla(lp,ls,dir)
.fi
.SH PARAMETERS
.SH DESCRIPTION
compute for the adjacencency description the arc array from 
pointer and node arrays
.SH SEE ALSO
compl2
