.TH connex 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME 
connex - connected components
.SH CALLING SEQUENCE
.nf
[nc,ncomp] = connex([g])
.fi
.SH PARAMETERS
.TP 2
g
: graph list, optional argument with default value \fVthe_g\fR
.TP 3
nc
: integer, number of connected components
.TP 6
ncomp
: row vector of connected components
.SH DESCRIPTION
\fVconnex\fR returns the number \fVnc\fR of connected components for the 
graph \fVg\fR and a row vector \fVncomp\fR giving the number of the connected 
component for each node.
.SH SEE ALSO
concomp, isconnex
