.TH l2adj 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME 
l2adj -  adjacency matrix from the adjacency description
.SH CALLING SEQUENCE
.nf
[a] = l2adj(lp,ls)
.fi
.SH PARAMETERS
.TP 10
lp,ls
:
.TP 10
a
:
.SH DESCRIPTION
computes the adjacency matrix from the adjacency description
.SH SEE ALSO
adj2l, l2g
