.TH TAN 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
tan - tangent
.SH CALLING SEQUENCE
.nf
[t]=tan(x)   
.fi
.SH PARAMETERS
.TP 10
x
: vector or symmetric matrix
.TP 10
t
: vector or matrix
.SH DESCRIPTION
the  elements  of vector  \fVt\fR   are  
the tangent of  the elements of vector \fVx\fR.
If \fVx\fR is a square and symmetric matrix \fVtan(x)\fR is the series.


