.TH and 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
and - logical and
.SH CALLING SEQUENCE
.nf
[b]=and(A)
.fi
.SH DESCRIPTION
\fVand(A)\fR is the logical AND of elements of 
the boolean matrix \fVA\fR. \fVand(A)\fR returns \fV%T\fR ("true")  iff 
all entries of \fVA\fR are \fV%T\fR.
.SH SEE ALSO
& | ~
