.TH deff 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
deff - on-line definition of function
.SH CALLING SEQUENCE 
.nf
deff('[s1,s2,...]=newmacro(e1,e2,....)',text)
.fi
.SH PARAMETERS
.TP 15
e1,e2,...,
: input variables.
.TP 15
s1,s2,..., 
: output variables.
.TP 15
text
: matrix of character strings
.SH DESCRIPTION
On-line definition of macro (user defined function): the name of the 
created function is \fVnewmacro\fR.
\fVtext\fR is a sequence of instructions usually set as a vector of 
character strings.
.LP
This command can be used inside a function and the new function
can be an input or output of any other function.
.LP
Usually, functions are defined in a file and loaded into Scilab by
\fVgetf\fR
.SH EXAMPLES
.nf
deff('[x]=myplus(y,z)','x=y+z')
.fi
.nf
deff('[x]=mymacro(y,z)',['instruc11,instruc12'; 'instruc21,x=instruc22'])
.fi
.SH SEE ALSO
getf, comp, exec, function

