.TH real G "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
real - real part
.SH CALLING SEQUENCE
.nf
[y]=real(x)
.fi
.SH PARAMETERS
.TP 10
x 
: real or complex vector or matrix
.TP 10
y
: real matrix
.SH DESCRIPTION
\fVreal(x)\fR is the real part of \fVx\fR (See \fV%i\fR to enter complex numbers).
.SH SEE ALSO
imag
