.TH save 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
save - saving variables
.SH CALLING SEQUENCE
.nf 
save(file-name, [,x1,..])
.fi
.SH DESCRIPTION
saves all current variables on the file \fVfile-name\fR.
.LP
\fVsave(file-name,x,y)\fR saves only \fVx,y\fR.
.LP
Saved  variables are loaded by the \fVload\fR command 
.SH SEE ALSO
load

