.TH macr2lst 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
macr2lst - macro to list conversion
.SH CALLING SEQUENCE
.nf
[txt]=macr2lst(macro-name)
.fi
.SH DESCRIPTION
This primitive converts a compiled Scilab macro \fVmacro-name\fR
into a list which codes the internal representation of
the macro. For use with \fVmac2for\fR. 


