.TH Minimum G "April 1993" "Scilab Group" "Scilab Function"
.so ../sci.an
.SH NAME
mini - minimum
.SH CALLING SEQUENCE
.nf
[m [,k]]=mini(A)
[m [,k]]=mini(A,'c') or [m [,k]]=mini(A,'r')
[m [,k]]=mini(A1,A2,...,An)
[m [,k]]=mini(list(A1,A2,...,An))
.fi
.SH PARAMETERS
.TP 10
A
: real vector or matrix.
.TP 10
A1,...,An
: a set of real vectors or matrices, all of the same size.
.SH DESCRIPTION
For \fVA\fR, a real  vector or matrix, \fVmini(A)\fR 
is the largest element 
\fVA\fR. \fV[m,k]=mini(A)\fR gives in addition the index of the minimum.
A second argument of type string \fV'r'\fR or \fV'c'\fR can be used : \fV'r'\fR
is used to get a row vector \fVm\fR such that \fVm(j)\fR contains the 
minimum of the \fVj\fR th column of A (\fVA(:,j)\fR), \fVk(j)\fR gives the row 
indice which contain the minimum for column \fVj\fR. \fV'c'\fR is used for the dual operation on the rows of \fVA\fR.

\fVm=mini(A1,A2,...,An)\fR, where all the \fVAj\fR are matrices of the same 
sizes,returns a vector or a matrix \fVm\fR of size \fVsize(m)=size(A1)\fR
such that \fVm(i)= max( Aj(i)), j=1,...,n\fR. \fV[m,k]=mini(A1,A2,...,An)\fR 
gives in addition the vector or matrix \fVk\fR. for a fixed \fVi\fR,
\fVk(i)\fR is the number of the first \fVAj(i)\fR achieving the minimum.

\fV[m,k]=mini(list(A1,...,An))\fR is an equivalent syntax of 
\fV[m,k]=mini(A1,A2,...,An)\fR
.SH EXAMPLE
.nf
[m,n]=mini([1,3,1])
[m,n]=mini([3,1,1],[1,3,1],[1,1,3])
[m,n]=mini(list([3,1,1],[1,3,1],[1,1,3]))
[m,n]=mini(list(1,3,1))
.fi
.SH SEE ALSO
sort, find, maxi

