.TH vp 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
vp - ? 
.SH DESCRIPTION
.nf 
 sys  : systeme dynamique
 sysn : nom du systeme donne sous forme de chaine de caratere
 pas  : pas d'integration
 Tmax : temps d'integration
 uequ : valeurs de u pour lesquelles on veut faire le calcul
 umac : chaine de caractere donnant en code Scilab
        la maniere de calculer le signal d'entree
        Ex umac="0.1*sin(t)" ou "0.1*bruit(t)"
.fi



