.TH maxcpp 1 "April 1993" "Scilab Group" "Scilab macro"
.so man1/sci.an
.SH NAME 
maxcpp -  maximum capacity path 
.SH CALLING SEQUENCE
.nf
[p,cap] = maxcpp(i,j,[g])
.fi
.SH PARAMETERS
.TP 4
i,j
: integers, node numbers
.TP
g
: graph list, optional argument with default value \fVthe_g\fR
.TP
p
: row vector of arc number, maximum capacity path 
.TP
cap
: capacity of the path
.SH DESCRIPTION
\fVmaxcpp\fR returns the maximum capacity path from node \fVi\fR to 
node \fVj\fR for the graph \fVg\fR.
