.TH pvm_error 1 "May 1998" "Scilab // Group" "Scilab function"
.so ../sci.an
.SH NAME
pvm_error - Prints  message  describing  an error  returned by a PVM call.
group.
.SH CALLING SEQUENCE
.nf
[errmsg] = pvm_error(err)
.fi
.SH PARAMETERS
.TP 5
err : integer, error code returned by a pvm function.
.TP 5
errmsg : string, the error message corresponding to the error code
err.


.SH DESCRIPTION
\fVpvm_error\fR returns the error message corresponding to an PVM error
code returned by a PVM call.


.SH EXAMPLE
.nf
[a] = pvm_error(0)
.fi
