.TH cosh 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
cosh - hyperbolic cosine
.SH CALLING SEQUENCE
.nf
[t]=cosh(x)
.fi
.SH PARAMETERS
.TP 10
x,t
: real or complex vectors
.SH DESCRIPTION
The  elements  of  vector \fVt\fR are  the  hyperbolic  cosine   
of  the corresponding entries of vector \fVx\fR.


