SHELL = /bin/sh
SCIDIR=../..
SCIDIR1=..\..


include ../../Makefile.incl

.SUFFIXES: .sci .bin $(SUFFIXES)

NAME = fraclablib
NAM = SCI/macros/fraclab


MACROS = \
	AtanH.sci\
	GeneWei.sci\
	MFAG_continuous.sci\
	MFAG_discrete.sci\
	MFAG_epsilon_eta.sci\
	MFAG_eta.sci\
	MFAG_net.sci\
	MakeCQF.sci\
	MakeQMF.sci\
	WT2DNbScales.sci\
	WT2DSize.sci\
	WT2DStruct.sci\
	WT2DVisu.sci\
	WT2Dext.sci\
	WTMultScales.sci\
	WTMultires.sci\
	WTNbScales.sci\
	WTOrigSize.sci\
	WTPump.sci\
	WTShrink.sci\
	WTStruct.sci\
	contwt.sci\
	contwtmir.sci\
	contwtspec.sci\
	cwtspec.sci\
	denois.sci\
	dilate.sci\
	dmt.sci\
	dwtspec.sci\
	fbmfwt.sci\
	fbmlevinson.sci\
	fft1d.sci\
	findWTLM.sci\
	flt.sci\
	gauss.sci\
	hotcmap.sci\
	icontwt.sci\
	idmt.sci\
	integ.sci\
	isempty.sci\
	lambdak.sci\
	mbmlevinson.sci\
	mexhat.sci\
	morlet.sci\
	mtlb_fftshift.sci\
	mtlb_hilbert.sci\
	mtlb_log2.sci\
	mtlb_rem.sci\
	nextpowQ.sci\
	oscillsing.sci\
	pseudoAW.sci\
	regdim.sci\
	sortup.sci\
	viewmat.sci

include ../Make.lib
