SHELL = /bin/sh

SCIDIR=../..
include ../../Makefile.incl

.SUFFIXES: .sci .bin $(SUFFIXES)

NAME = utillib
NAM = util

MACROS = sysconv.sci readc_.sci lin.sci \
	halt.sci bloc2exp.sci \
	pol2tex.sci texprint.sci bloc2ss.sci \
	cmb_lin.sci eval.sci evstr.sci solve.sci \
	trianfml.sci trisolve.sci sci2map.sci \
	logspace.sci linspace.sci ssprint.sci ssrand.sci \
	sysdiag.sci syslin.sci syssize.sci trfmod.sci manedit.sci \
	x_matrix.sci typeof.sci isdef.sci zeros.sci edit.sci \
	g_ones.sci g_rand.sci g_eye.sci g_diag.sci g_triu.sci g_tril.sci \
	g_size.sci colnew.sci g_inv.sci g_det.sci g_clean.sci g_sort.sci \
	g_real.sci g_imag.sci g_int.sci g_floor.sci g_ceil.sci g_pow.sci \
	getvalue.sci usermenu.sci macrovar.sci input.sci sci2exp.sci \
	demos.sci whereami.sci sp_sum.sci po_sum.sci c_sort.sci \
	printf.sci fprintf.sci sprintf.sci scanf.sci fscanf.sci sscanf.sci \
	xdialog.sci unix_g.sci unix_s.sci unix_x.sci unix_w.sci \
	x_choices.sci odeoptions.sci g_sin.sci g_cos.sci \
	g_round.sci g_exp.sci g_sqrt.sci whos.sci newest.sci

include ../Make.lib
