.TH disp 1 "April 1993" "Scilab Group" "Scilab Function"
.so ../sci.an
.SH NAME
disp - displays variables 
.SH CALLING SEQUENCE
.nf
disp(x1,[x2,...xn]) 
.fi
.SH DESCRIPTION
displays \fVxi\fR with the current format. \fVxi\fR's are arbitrary
objects (matrices of constants, strings, functions, lists, ...)
.SH SEE ALSO
write, read, print, string

