.TH floor 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
floor - rounding down
.SH CALLING SEQUENCE
.nf
[y]=floor(x)
.fi
.SH PARAMETERS
.TP
x 
: a real matrix
.TP 
y
: integer matrix
.SH DESCRIPTION
\fVfloor(x)\fR returns an integer matrix made of nearest rounded down integers.
.SH SEE ALSO
round, floor, ceil

