.TH getf 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
getf - loading of macro
.SH CALLING SEQUENCE
.nf
getf('file-name' [,'c'])
.fi
.SH DESCRIPTION
loads one or several 
macros which are defined in the file \fV'file-name'\fR.
The string \fV'c'\fR means that the macros are to be compiled when loaded.
(see \fVcomp\fR).
The first line of the file must be as follows:
.nf
function [s1,s2,..,slhs]=macr(e1,e2,...,erhs)  
.fi
\fVei\fR are input variables and \fVsi\fR are output variables.
.SH SEE ALSO
comp, exec

