.TH help 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
help - on-line help command
.SH CALLING SEQUENCE
.nf
	help word
	help 'string'
.fi
.SH DESCRIPTION
Scilab's manual. Needs the Unix command "man" and "xman".
.LP
See the script files \fVSCIDIR/bin/scihelp\fR and \fVSCIDIR/bin/xscihelp\fR.
.SH SEE ALSO
apropos


