.TH * 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
* - multiplication 
.SH DESCRIPTION
Multiplication. Usual meaning. Valid for constant,
boolean, polynomial and rational matrices.
.LP
Element-wise multiplication is denoted \fVx.*y\fR
.LP
Kronecker product is \fVx.*.y\fR
.SH SEE ALSO
mulf

