.TH strings 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
"Scilab object:string" - character strings
.SH DESCRIPTION
.LP
Strings are defined as \fV'string'\fR (between quotes);
matrices of strings are defined as usual constant matrices.
.LP
Concatenation of two strings is made by a \fV+\fR : \fVstring1+string2\fR.
.SH EXAMPLE
.nf
['this','is'; 'a 2x2','matrix']
'matrix'=='mat'+'rix'
.fi
.SH SEE ALSO
part, length, strcat
