.TH exar2 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
exar2 - armax identification example 
.SH CALLING SEQUENCE
.nf
[z,zd,u,ar]=exar2()
.fi 
.SH DESCRIPTION
ARMAX example ( K.J. Astrom). A simulation of a bidimensional
version of the example of exar1.
.SH SEE ALSO
exar1
