.TH gbruit 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
gbruit - noise generation 
.SH CALLING SEQUENCE
.nf
[]=gbruit(pas,Tmax,sig)
.fi 
.SH DESCRIPTION
generates a Scilab macro \fV[b]=bruit(t)\fR
where \fVbruit(t)\fR is a piecewise constant function 
( constant on  \fV[k*pas,(k+1)*pas]\fR ). The value on each constant 
interval are random values from  i.i.d  Gaussian variables of 
standard deviation sig. The function is constant for \fVt<=0\fR and 
\fVt>=Tmax\fR.
