"  adj_lists   - compute adjacency lists ",
"  check_graph   - check a Scilab graph-list ",
"  circuit   - find a circuit or the rank function in a directed graph ",
"  con_nodes   - set of nodes of a connected component ",
"  connex   - connected components ",
"  find_path   - find a path between two nodes ",
"  graph-list   - description of graph ",
"  graph_2_mat   - node-arc incidence matrix from graph ",
"  is_connex   - connectivity test ",
"  load_graph   - load a graph ",
"  make_graph   - make a graph-list ",
"  mat_2_graph   - graph from node-arc incidence matrix ",
"  max_cap_path   - maximum capacity path ",
"  max_flow   - maximum flow between two nodes ",
"  metanet   - open a Metanet window ",
"  min_lcost_cflow   - minimum linear cost constrained flow ",
"  min_lcost_flow1   - minimum linear cost flow ",
"  min_lcost_flow2   - minimum linear cost flow ",
"  min_qcost_flow   - minimum quadratic cost flow ",
"  min_weight_tree   - minimum weight spanning tree ",
"  netwindow   - choose a Metanet window ",
"  netwindows   - get the numbers of Metanet windows ",
"  nodes_2_path   - path from a set of nodes ",
"  path_2_nodes   - set of nodes from a path ",
"  plot_graph   - plot a graph ",
"  plot_graph1   - plot a graph ",
"  plot_graph2   - plot a graph ",
"  save_graph   - save a graph ",
"  shortest_path   - shortest path ",
"  show_arcs   - highlight a set of arcs ",
"  show_graph   - display a graph ",
"  show_nodes   - highlight a set of nodes ",
"  strong_con_nodes   - set of nodes of a strong connected component ",
"  strong_connex   - strong connected components ",
"  trans_closure   - transitive closure ",
