.TH CLKSOMV_f 5 "Janvier 1996" "Scilab Group" "Scicos Block"
.so ../sci.an
.SH NAME
CLKSOMV_f - Scicos event addition block
.SH DIALOGUE PARAMETERS
None.
.SH DESCRIPTION
This block is an event addition block with up to three inputs. The
output reproduces 
the events on all the input ports. Strictly speaking, CLKSOMV is not a
Scicos block because it is discarded at the compilation phase. The
inputs and output of CLKSOMV are synchronized. 









