.TH ROOTS G "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an 
.SH NAME
roots - roots of polynomials
.SH CALLING SEQUENCE
.nf
[x]=roots(p)
.fi
.SH PARAMETERS
.TP
p 
: polynomial with real or complex coefficients
.SH DESCRIPTION
\fVx=roots(p)\fR returns the complex vector x the roots of the 
polynomial \fVp\fR
.SH SEE ALSO 
poly.

