# Linux Makefile
SCIDIR = ../../..

MEXSOURCES = temptst.cpp

MEXNAMES = temptst

OTHERSOURCES = temptst2.cpp

#prefix lib is compulsory!
LIBRARY = libtemptst

include $(SCIDIR)/Makefile.incl
include Makemexcpp


