.TH gpeche 1 "April 1993" "Scilab Group" "Scilab Function"
.SH NAME
gpeche - a fishing program
.SH DESCRIPTION
pour une loi de commande uk
calcule la trajectoire associee xk
imprime le valeur du cout
calcule une nouvelle valeur de commande
.SH PCHE
.SH DESCRIPTION
.nf
[ut]=peche(t)
.fi
la loi de commande u(t) constante par morceaux
construite sur la loi de comande discrete uk
.SH PECHEP
.nf
[pdot]=pechep(t,p)
.fi


