.TH xload 2 "April 1993" "Scilab Group" "Scilab Function"
.so ../sci.an
.SH NAME
xload - load a saved graphic
.SH CALLING SEQUENCE
.nf
xload('file-name' [, win-num] ) 
.fi
.SH PARAMETERS 
.TP 15
win-num 
: an integer ( optional argument ) which stands for the graphic window
in which the graphics are to be loaded.
.SH DESCRIPTION
This function is used to reload the graphics contained in the file \fV'file-name'\fR
in the graphic-window \fVwin-num\fR.
The graphics are stored in a binary file in a  machine independent way ( using the 
xdr library). 
.SH SEE ALSO
xsave 
.SH AUTHOR
J.Ph.C..





