.TH alufunctions 2 "April 1993" "Scilab Group" "Scilab keyword"
.SH NAME
alufunctions - description and number of pixel drawing modes.
.SH DESCRIPTION
src is the source ie the "value of the pixel" which we want to draw.
dst is the destination ie "value of the pixel" which is already drawn.

.RS
 0: clear ie "0"
.RE
.RS
 1: and ie "src AND dst"
.RE
.RS
 2: and reverse ie "src AND NOT dst"
.RE
.RS
 3: copy ie "src"
.RE
.RS
 4: and inverted ie "(NOT src) AND dst"
.RE
.RS
 5: noop ie "dst"
.RE
.RS
 6: xor ie "src XOR dst"
.RE
.RS
 7: or ie "src OR dst"
.RE
.RS
 8: nor ie "(NOT src) AND (NOT dst)"
.RE
.RS
 9: equiv ie "(NOT src) XOR dst"
.RE
.RS
10: invert ie "NOT dst"
.RE
.RS
11: or reverse ie "src OR (NOT dst)"
.RE
.RS
12: copy inverted ie "NOT src"
.RE
.RS
13: or inverted ie "(NOT src) OR dst"
.RE
.RS
14: nand ie "(NOT src) OR (NOT dst)"
.RE
.RS
15: set ie "1"
.RE
