.TH Matplot 2 "April 1993" "Scilab Group" "Scilab Function"
.so ../sci.an
.SH NAME
Matplot - 2D plot of a matrix using colors 
.SH CALLING SEQUENCE
.nf
Matplot(a,[strf,rect,nax])
.fi
.SH PARAMETERS
.TP 3
a
: real matrix of size (n1,n2).
.TP
strf,rect,nax
: optional arguments, see \fVplot2d\fR.
.SH DESCRIPTION
The entries of matrix \fVint(a)\fR are used as colormap entries in 
the current colormap. The color associated to \fVa(i,j)\fR is used 
do draw a small square of length 1 with center at location 
\fV(x=j,y=(n2-i+1))\fR.

Enter the command \fVMatplot()\fR to see a demo.
.SH EXAMPLE 
.nf 
Matplot([1 2 3;4 5 6])
// draw the current colormap 
Matplot((1:xget("lastpattern")))
.fi
.SH SEE ALSO
colormap, plot2d, Matplot1
.SH AUTHOR
J.Ph.C.
