.TH setfield 1 "September 1999" "Scilab Group" "Scilab Function"
.so ../sci.an
.SH NAME
setfield -  list field insertion
.SH CALLING SEQUENCE
.nf
setfield(i,x,l)
.fi
.SH PARAMETERS
.TP 15
x
: matrix  of any  possible types
.TP 15
l
: list, tlist or mlist variable
.TP 15
i
: field index, see insertion for more details.
.SH DESCRIPTION
This function is an equivalent of \fVl(i)=x\fR syntax for field
extraction with the only difference that it also applies to
\fVmlist\fR objects.
.SH EXAMPLE
.nf
l=list(1,'qwerw',%s)
l(1)='Changed'
l(0)='Added'
l(6)=['one more';'added']
//

a=hypermat([2,2,2],rand(1:2^3));// hypermatrices are coded using mlists
setfield(3,1:8,a);a // set the filed value to 1:8
.fi
.SH SEE ALSO
insertion
