.TH savewave 1 "April 1993" "Scilab Group" "Scilab Function"
.so ../sci.an
.SH NAME
savewave - save data into a sound <<wav>> file.
.SH CALLING SEQUENCE
.nf
x=savewave('file-name' [, rate ]);
.fi
.SH PARAMETERS
.TP
x
: vector 
.TP
rate
: a scalar. 22050 is the default value.
.SH DESCRIPTION
save x into a  wav sound file. you can transform other sound files
into wav file with the \fVsox\fR program.
.SH SEE ALSO
loadwave, soundsec, analyze, mapsound



