#!/bin/sh -
#
# Copyright (c) 1980 Regents of the University of California.
# All rights reserved.  The Berkeley software License Agreement
# specifies the terms and conditions for redistribution.
#
#       @(#)makewhatis.sh 1.13 89/06/15 SMI; from UCB 5.3 3/29/86
#
/usr/bin/catman -M `pwd` -w 12345678

