.TH markp2ss 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an 
.SH NAME
markp2ss - Markov parameters to state-space
.SH CALLING SEQUENCE
.nf
[sl]=markp2ss(markpar,n,nout,nin)
.fi
.SH PARAMETERS
.TP 10
markpar
: matrix
.TP 15
n,nout,nin
: integers
.TP 10
Sl
: \fVsyslin\fR list
.SH DESCRIPTION
given a set of \fVn\fR Markov parameters stacked in the (row)-matrix 
\fVmarkpar\fR of size \fVnout\fRX\fV(n*nin) markp2ss\fR
returns a state-space linear system \fVsl\fR (\fVsyslin\fR list) 
such that with \fV[A,B,C,D]=abcd(sl)\fR:
.nf
   C*B = markpar(1:nout,1:nin),
   C*A*B =marpar(1:nout,nin+1:2*nin),....
.fi
