SHELL = /bin/sh

SCIDIR=../..
include ../../Makefile.incl

.SUFFIXES: .sci .bin $(SUFFIXES)

NAME = polylib
NAM = calpol

MACROS = cmndred.sci coffg.sci colcompr.sci \
	denom.sci derivat.sci determ.sci detr.sci \
	diophant.sci gcd.sci hermit.sci horner.sci \
	hrmt.sci htrianr.sci invr.sci lcm.sci \
	numer.sci pdiv.sci pol2des.sci \
	pol2str.sci polfact.sci routh_t.sci rowcompr.sci \
	sylm.sci systmat.sci pfactors.sci factors.sci

include ../Make.lib
