.TH titlepage 2 "April 1993" "Scilab Group" "Scilab Function" 
.so man1/sci.an
.SH NAME
titlepage  - display a matrix of strings 
.SH CALLING SEQUENCE
.nf
titlepage(str)
.fi
.SH PARAMETERS
.TP 10
str
: matrix of strings
.SH DESCRIPTION
\fVtitlepage(str)\fR displays the matrix \fVstr\fR in  the current graphic window
with a size font as large as possible
.SH SEE ALSO
xtitle
.SH AUTHOR
S. S.


