SHELL = /bin/sh

SCIDIR=../..
SCIDIR1=..\..

include ../../Makefile.incl

.SUFFIXES: .sci .bin $(SUFFIXES)

NAME = commlib
NAM = SCI/macros/comm

MACROS = ExecScilab.sci ExeclScilab.sci

include ../Make.lib
