.TH netwindow 1 "September 1995" "Scilab Group" "Scilab function"
.so man1/sci.an
.SH NAME
netwindow - choose a Metanet window
.SH CALLING SEQUENCE
.nf
netwindow(window)
.fi
.SH PARAMETERS
.TP 7
window
: integer, window number
.SH DESCRIPTION
This function is used to change the \fVMetanet\fR window. Each \fVMetanet\fR 
window has a window number returned by the \fVmetanet\fR function. To use 
the \fVMetanet\fR window associated to window number \fVwindow\fR, use 
\fVnetwindow(window)\fR. The numbers of existing windows are given by the 
function \fVnetwindows\fR.
.SH SEE ALSO
metanet, netwindows
