.TH getversion 1 "April 2000" "Scilab Group" "Scilab Function"
.so ../sci.an
.SH NAME
getversion - get Scilab version name
.SH CALLING SEQUENCE
.nf
version=getversion()
.fi
.SH PARAMETERS
.TP 15
version
: a string
.SH DESCRIPTION
return in \fVversion\fR the Scilab version name
.SH EXAMPLE
.nf
getversion()
.fi


