.TH x_message_modeless 1 "April 1993" "Scilab Group" "Scilab Function"
.so ../sci.an
.SH NAME
x_message_modeless - X window modeless message
.SH CALLING SEQUENCE
.nf
x_message_modeless(strings) 
.fi
.SH PARAMETERS
.TP
strings
: vector of characters strings to be displayed

.SH DESCRIPTION
for displaying a message (information, user-guide ...). The function
returns immediately. The message window is killed when "Ok" button is
clicked. 

.SH EXAMPLES
.nf
 x_message_modeless(['This is a modeless message'
                     'Scilab may continue computation'
                     ' '
                     'Click on ""Ok"" to close the message'])
 x_message_modeless('Now two message windows are opened')
.fi
.SH SEE ALSO
x_dialog, x_mdialog, x_message
