.TH modulo 1 "April 1993" "Scilab Group" "Scilab Function"
.so ../sci.an
.SH NAME
modulo - arithmetic remainder modulo m
.SH CALLING SEQUENCE
.nf
i=modulo(n,m)
.fi
.SH PARAMETERS
n,m:
integers
.SH DESCRIPTION
computes \fVi= n (modulo m)\fR i.e. remainder
of \fVn\fR divided by \fVm\fR (\fVn\fR and \fVm\fR integers).
.LP
.Vb i= n - m .* int (n ./ m)
.SH EXAMPLE
.nf
n=[1,2,10,15];m=[2,2,3,5];
modulo(n,m)
.fi

