.TH plot3di1 2 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
plot3di1 - gray level plotting of a surface with interactive view selection
.SH CALLING SEQUENCE
.nf
plot3di1(x,y,z,[theta,alpha,leg,flag,ebox])
.fi
.SH PARAMETERS
see \fVplot3d\fR (\fVmode\fR unused)
.SH DESCRIPTION
plots a surface  \fVz=f(x,y)\fR (points)


Pick a point within the graphic window (Left mouse button) and drag
the mouse (theta
increases for left to right move and alpha increases for down to up
move). When view is ok click with the left button to have the surface
drawn. click rigth button  to exit.


For Pos and Fig drivers plot3di woks just like plot3d

.SH EXAMPLE
enter the command \fVplot3di1()\fR to see a demo .
.SH AUTHOR
J.Ph.C.


