"  artest   - arnold dynamical system ",
"  bifish   - shows a bifurcation diagram in a fish population discrete time model  ",
"  boucle   - phase portrait of a dynamical system with observer ",
"  chaintest   - a three-species food chain model  ",
"  gpeche   - a fishing program ",
"  fusee   - a set of Scilab macro for a landing rocket problem  ",
"  lotest   - demo of the Lorenz attractor ",
"  mine   - a mining problem  ",
"  obs_cont   - a controlled-observed system ",
"  portr3d   - 3 dimensional phase portrait. ",
"  portrait   - 2 dimensional phase portrait. ",
"  recur   - a bilinear recurrent equation  ",
"  systems    - a collection of dynamical system  ",
"  tangent   - linearization of a dynamical system at an equilibrium point  ",
"  tdinit   - interactive initialisation of the tdcs dynamical systems ",
