.TH denom 8 "April 1993" "Scilab Group" "Scilab Function"
.so ../sci.an 
.SH NAME
denom - denominator
.SH CALLING SEQUENCE
.nf
den=denom(r)
.fi
.SH PARAMETERS
.TP
r
: rational or polynomial or constant matrix.
.TP
den
: polynomial matrix
.SH DESCRIPTION
.Vb den=denom(r) 
returns the denominator of a rational matrix.
.LP
Since rationals are internally represented as \fVr=list(['r','num','den','dt'],num,den,[])\fR,
\fVdenom(r\fR) is the same as \fVr(3)\fR or \fVr('den')\fR .
.SH SEE ALSO
numer

