.TH detrX 1 "April 1993" "Scilab Group" "Scilab Function"
.so ../sci.an 
.SH NAME
detr - polynomial determinant
.SH CALLING SEQUENCE
.nf
d=detr(h)
.fi
.SH PARAMETERS
.TP
h
: polynomial or rational square matrix
.SH DESCRIPTION
.Vb d=detr(h) 
returns the determinant \fVd\fR of the polynomial or 
rational function matrix \fVh\fR. Based on Leverrier's algorithm.
.SH SEE ALSO
det, determ


