.TH numerX 1 "April 1993" "Scilab Group" "Scilab Function"
.so ../sci.an 
.SH NAME
numer - numerator
.SH CALLING SEQUENCE
.nf
NUM=numer(R)
.fi
.SH PARAMETERS
.TP
R
: rational matrix
.SH DESCRIPTION
Utility fonction. \fVNUM=numer(R)\fR returns the numerator \fVNUM\fR of a rational 
function matrix \fVR\fR (\fVR\fR may be also a constant or polynomial matrix).
\fVnumer(R)\fR is equivalent to \fVR(2)\fR or \fVR('num')\fR
.SH SEE ALSO
denom




