#!/bin/csh 
if ( $#argv != 0 ) then 
if ( $#argv == 1 ) then 
grep -i include $* $* | grep -i "\.h'"| sort -u | sed -e "s/'//g" -e "s/include//" -e "s/INCLUDE//" -e "s/\.f/.o/"  >>! Makefile
else 
grep -i include $* | grep -i "\.h'"| sort -u | sed -e "s/'//g" -e "s/include//" -e "s/INCLUDE//" -e "s/\.f/.o/"  >>! Makefile
endif
echo "dependencies generated"
endif


