#!/bin/sh 
#-------------------------------------------------------
# scilib scidir name nam 
# To create the library name  stored in macro/nam
# The file names is supposed to exist (See Imakefiles)
#-------------------------------------------------------
SCI=$1; export SCI
echo generating $2.bin
mv $SCI/scilab.star $SCI/scilab.save
trap "rm -f $SCI/scilab.star;mv $SCI/scilab.save $SCI/scilab.star;exit 1"  1 2 13 15
echo ' ' > $SCI/scilab.star;
echo "write(%io(2),' ');predef(0);$2=lib('SCI/macros/$3/');\
	u=file('open','lib','unknown','unformatted');\
	save(u,$2);quit"|$SCI/bin/scilex|sed 1,/--\>/d 1>report 2>&1
rm -f $SCI/scilab.star;
if (grep error report 1> /dev/null  2>&1);
then cat report;echo " " 
   echo see `pwd`/report for more informations
   grep libok report>/dev/null; 
else rm -f report;
fi
mv $SCI/scilab.save $SCI/scilab.star
exit 0
