.TH obs_cont 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
obs_cont - a controlled-observed system
.SH CALLING SEQUENCE
.nf
[macr]=obscont(sysn)
.fi
.SH PARAMETERS
.TP
sysn 
: A scilab string which gives the name of the controled system.
.TP
gaincom,gainobs 
: column vectors giving the requested gains 
.TP
macr
: a new Scilab macrs which simulates the controled observed system.
.nf
[x1dot]=macr(t,x1,abruit,pas,n)
x1=[x;xchap],
.fi 
.SH DESCRIPTION 
Thi macros return a new macro which computes the controled observed version 
of a linearised system around the \fV(xe,ue)\fR point.

before calling this macro, a noise vector \fVbr\fR should be created.
the equilibrium point \fV(xe,ue)\fR should be given as a global Scilab.
 the linearised system $f,g,h$ and the two  gain matrices \fVl,k\fR are returned as global Scilab data.
.SH EXAMPLE
.nf
    pas=10;n=200;
    br=rand(1,n)
    ode([x0;xchap0],0,pas*(0:n),list(macr,1.0,pas,n));
.fi


