.TH lindquist 1 "April 1993" "Scilab Group" "Scilab Function"
.so ../sci.an
.SH NAME
lindquist - Lindquist's algorithm
.SH CALLING SEQUENCE
.nf
[P,R,T]=lindquist(n,H,F,G,R0)
.fi
.SH PARAMETERS
.TP 16
n
: number of iterations.
.TP
H, F, G
: estimated triple from the covariance sequence of \fVy\fR.
.TP
R0
: E(yk*yk')
.TP
P
: solution of the Riccati equation after n iterations.
.TP
R, T
: gain matrices of the filter.
.SH DESCRIPTION
computes iteratively the minimal solution of the algebraic
Riccati equation and gives the matrices \fVR\fR and \fVT\fR of the 
filter model, by the Lindquist's algorithm.
.SH AUTHOR
G. Le V.
.SH SEE ALSO
srfaur, faurre, phc
