.TH sincd 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
sincd - sinc function
.SH CALLING SEQUENCE
.nf
[s]=sincd(n,flag)
.fi
.SH PARAMETERS
.TP 10
n
: integer
.TP
flag
: if \fVflag = 1\fR the function is centered around the origin;
if \fVflag = 2\fR the function is delayed by \fV%pi/(2*n)\fR
.TP
s
: vector of values of the function on a dense grid of frequencies
.SH DESCRIPTION
macro which calculates the function \fVSin(N*x)/Sin(x)\fR
.SH AUTHOR
G. Le V.
