.TH abs G "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
abs -  absolute value, magnitude
.SH CALLING SEQUENCE
.nf
[t]=abs(x)
.fi
.SH PARAMETERS
.TP
x 
: real or complex vector or matrix
.TP
t
: real vector or matrix
.SH DESCRIPTION
\fVabs(x)\fR is the absolute value of the elements of \fVx\fR. When
\fVx\fR is complex, \fVabs(x)\fR is the magnitude of the elements . 
