.TH cotg 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
cotg - cotangent
.SH CALLING SEQUENCE
.nf
[t]=cotg(x)
.fi
.SH PARAMETERS
.TP 10
x,t
: real or complex vectors
.SH DESCRIPTION
The  elements  of  vector \fVt\fR are  the  cotangents
of  the corresponding entries of vector \fVX\fR.


