.TH prod G "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
prod - product
.SH CALLING SEQUENCE
.nf
[y]=prod(x)
.fi
.SH PARAMETERS
.TP
x 
: real or complex vector or matrix
.TP
y
: real or complex scalar
.SH DESCRIPTION
For vectors and matrices, \fVprod(x)\fR is the product of the elements 
of x, e.g. \fVprod(1:n)\fR is n!
.SH SEE ALSO
sum
