.TH setmenu 3 "December 1995" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
setmenu - interactive button or menu activation
.SH CALLING SEQUENCE
.nf
setmenu(button [,nsub]) 
setmenu(gwin,button [,nsub])
.fi
.SH PARAMETERS
.TP
button
: a character string. The button name
.TP
gwin
: integer. The number of graphic window where the button is  installed
.TP
nsub
: integer. The number of submenu to de-activate (if any). If button
has no sub-menu, \fVnsub\fR is ignored

.SH DESCRIPTION
The function allows the user to make active  buttons or menus created by
\fVaddmenu\fR in the main or graphics windows command panels.
.SH EXAMPLE
.nf
addmenu('foo')
setmenu('foo')
.fi
.SH SEE ALSO
delmenu, unsetmenu, addmenu
