.TH solve 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
solve - symbolic linear system solver
.SH CALLING SEQUENCE
.nf
[x]=solve(A,b)
.fi
.SH PARAMETERS
.TP
A,b,c
: matrix (resp. vectors) of character strings
.SH DESCRIPTION
solves \fVA*x = b\fR when \fVA\fR is an upper triangular matrix
made of character strings.
.SH SEE ALSO
trianfml

