.TH sort 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
sort - decreasing order sorting
.SH CALLING SEQUENCE
.nf
[s, [k]]=sort(v)
.fi
.SH DESCRIPTION
sorts \fVv\fR (decreasing order).
\fV[s,k]=sort(v)\fR give in addition the indices of entries of \fVs\fR in \fVv\fR.
.SH SEE ALSO
find

