.TH sum 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
sum - sum  of vector/matrix entries
.SH CALLING SEQUENCE
.nf
[y]=sum(x)
.fi
.SH PARAMETERS
.TP 10
x
: vector or matrix (real, complex or polynomial)
.TP 10
y
: scalar or vector
.SH DESCRIPTION
For a vector or a matrix \fVx\fR , \fVsum(x)\fR is the sum of all its entries.
.SH SEE ALSO
prod
