.TH plot3d1 2 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
plot3d1 - gray level plotting of a surface 
.SH DESCRIPTION
.nf
plot3d1(x,y,z,[theta,alpha,leg,flag,ebox])
.fi
.SH PARAMETERS
see \fVplot3d\fR (\fVmode\fR unused)
.SH DESCRIPTION
plots a surface  \fVz=f(x,y)\fR (points)
.SH EXAMPLE
enter the command \fVplot3d1()\fR to see a demo .
.SH AUTHOR
J.Ph.C.


