.TH xs2fig 2 "April 1993" "Scilab Group" "Scilab Function" 
.so man1/sci.an
.SH NAME
xs2fig - send graphics to a file in Xfig syntax
.SH CALLING SEQUENCE
.nf
xs2fig(win_num,filen)
.fi
.SH PARAMETERS
.TP 10
win_num 
: an integer scalar or vector 
.TP 10
filen 
: string (file name).
.SH DESCRIPTION
This function will send the recorded graphics of the
window \fVwin_num\fR in the file \fVfilen\fR in Xfig syntax 
This function will work only if the selected 
driver is \fV"Rec"\fR





