.TH plot_graph1 1 "September 1995" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
plot_graph1 - plot a graph
.SH CALLING SEQUENCE
.nf
plot_graph1(g,[orx,ory,w,h])
.fi
.SH PARAMETERS
.TP 2
g
: graph-list
.TP 12
orx,ory,w,h
: real values defining the plotting rectangle
.SH DESCRIPTION
Plot of a graph with different types of nodes, multiple arcs and loops
(without arrows). The size of the plot is automatically
computed with the coordinates of the nodes. The optional parameters 
\fV[orx,ory,w,h]\fR (upper-left point, width, height) define a rectangle
for a better definition of the window or for zooming on a part of
the graph
.SH EXAMPLE
.nf
// simple graph for comparing plot_graph, plot_graph1 and plot_graph2
ta=[2 2 1 1 2 4 3 3 4];
he=[2 2 3 2 3 2 1 2 1];
g=make_graph('foo',1,4,ta,he);
g('node_type')=[1 1 1 2];
g('node_x')=[73 737 381 391]; g('node_y')=[283 337 458 142];
g('node_color')=[3 3 3 11];
g('node_diam')=[30 30 30 60];
g('edge_color')=[10 0 2 6 11 11 0 0 11];
xbasc();
plot_graph(g);
x_message('plot_graph');
xbasc();
plot_graph1(g);
x_message('plot_graph1');
xbasc();
plot_graph2(g);
x_message('plot_graph2');
xbasc();
plot_graph2(g,200,-470,350,450);
.fi
.SH SEE ALSO
plot_graph, plot_graph2
