.TH help 1 "April 1993" "Scilab Group" "Scilab Function"
.so ../sci.an
.SH NAME
help - on-line help command
.SH CALLING SEQUENCE
.nf
	help word
.fi
.SH DESCRIPTION
To each documented word corresponds a \fVword.cat\fR ascii file. these files
are organised within directories (chapters). Each chapter must contain
\fV*.cat\fR files and a \fVwhatis\fR file with one line for each documented word
in the chapter. Each line must have the following format :

.nf
word - quick description
.fi

List of chapter directories is given in a scilab variable
\fV%helps\fR. \fV%helps\fR a two column matrix of strings. Each line
is formed as follow :
.nf
chapter_path    chapter_title
.fi
.LP
\fV%helps\fR default value is set by scilab.star file. If you want
to add new help chapters you have to add new lines \fV%helps\fR
variables for example in your .scilab startup file.
.LP
Note that, once the help has been used, new additions to \fV%helps\fR
are not taken into account.
.LP
See also Scilab's manual 
.SH SEE ALSO
apropos, man, formatman


