.TH tdinit 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
tdinit - interactive initialization of the tdcs dynamical systems
.SH CALLING SEQUENCE 
.nf
tdinit()
.fi
.SH DESCRIPTION 
This macro can be used to interactively define the parameters needed 
by the dynamical systems described in systems
.RS
.IP "bioreactor model"
.IP "competition model"
.IP "system with limit cycle"
.IP "linear system"
.IP "quadratic model"
.IP "linear system with a feedback"
.IP "pray predatory model initialization"
.RE
.SH SEE ALSO
portrait, systems
