SHELL = /bin/sh

SUBDIRS = intro lmitool metanet signal scicos

all::
	@case '${MFLAGS}' in *[ik]*) set +e;; esac; \
	for i in $(SUBDIRS) ;\
	do \
		(cd $$i ; echo "making" doc "in doc/$$i..."; \
			$(MAKE) $(MFLAGS) all); \
	done

world: all

distclean::
	@case '${MFLAGS}' in *[ik]*) set +e;; esac; \
	for i in $(SUBDIRS) ;\
	do \
		(cd $$i ; echo "making distclean in doc/$$i..."; \
		$(MAKE) $(MFLAGS)  distclean); \
	done

clean::
	@case '${MFLAGS}' in *[ik]*) set +e;; esac; \
	for i in $(SUBDIRS) ;\
	do \
		(cd $$i ; echo "making clean in doc/$$i..."; \
		$(MAKE) $(MFLAGS) clean); \
	done
