.TH degree 1 "April 1993" "Scilab Group" "Scilab Function"
.so ../sci.an
.SH NAME
degree - degree of polynomial matrix
.SH CALLING SEQUENCE
.nf
[D]=degree(M) 
.fi
.SH PARAMETERS
.TP 10
M
: polynomial matrix
.TP
D
: integer matrix
.SH DESCRIPTION
returns the matrix of highest degrees of \fVM\fR.
.SH SEE ALSO
poly, coeff, clean

