.TH intc 1 "April 1993" "Scilab Group" "Scilab Function"
.so ../sci.an 
.SH NAME
intc - Cauchy integral
.SH CALING SEQUENCE
.nf
[y]=intc(a,b,f)  
.fi 
.SH PARAMETERS
.TP
a,b
: two complex numbers
.TP
f
: "external" function
.SH DESCRIPTION
If \fVf\fR is  a complex-valued function,\fV intc(a,b,f) \fR
computes the integral from \fVa\fR to \fVb\fR of \fVf(z)dz\fR along the  
straight line \fVa b\fR of the complex plane.
.SH SEE ALSO
intg, intl
.SH AUTHOR
F. D.
