<LI><A NAME="tex2html4" HREF="node19.html#247">This window must be edited to define problem name and the
name of variables used.</A>
<LI><A NAME="tex2html5" HREF="node19.html#252">For the example at hand the result of the editing should
look something like this.</A>
<LI><A NAME="tex2html6" HREF="node19.html#339">This is the skeleton of the solver function and the
evaluation function generated by <TT>LMITOOL</TT> using the names
defined previously.</A>
<LI><A NAME="tex2html7" HREF="node19.html#260">After editing, we obtain.</A>
<LI><A NAME="tex2html8" HREF="node19.html#262">A file is proposed in which the solver and evaluation
functions are to be saved. You can modify it if you want.</A>
