"  adj2l   - from adjacency matrix to adjacency vectors ",
"  anpath   - path between two nodes ",
"  anshp   - arc number shortest path   ",
"  circuit   - circuit ",
"  compht   - from adjacency vectors to head-tail vectors ",
"  compl2   - from directed to undirected adjacency vectors ",
"  compla   - from adjacency pointer and node arrays to arc array ",
"  concomp   - node set of a connected component   ",
"  connex   - connected components ",
"  createg   - new graph from a graph list ",
"  gmaxflow   - global maximum flow   ",
"  graph_list   - description of the list representing a graph in Scilab ",
"  isconnex   - connectivity test   ",
"  l2adj   - from adjacency vectors to adjacency matrix ",
"  l2g   - graph from an adjacency description ",
"  loadg   - load an existing graph   ",
"  lshp   - length shortest path   ",
"  makeund   - from directed to undirected graph  ",
"  maxcpp   - maximum capacity path  ",
"  maxflow   - maximum flow between two nodes   ",
"  metanet   - execute Metanet ",
"  mincf0   - minimum linear cost flow   ",
"  mincfr   - minimum linear cost flow (relaxation method) ",
"  minicf   - minimum linear cost for imposed flow   ",
"  minqflow   - minimal quadratic cost flow ",
"  mintree   - minimal weight tree  ",
"  netwindow   - change Metanet window ",
"  netwindows   - get Metanet windows numbers ",
"  ns2p   - path from a node sequence ",
"  p2ns   - node sequence of a path ",
"  concomp   - node set of a strong connected component   ",
"  sconnex   - strong connected components  ",
"  showns   - highlight a set of nodes ",
"  showp   - highlight a set of arcs  ",
"  transclo   - transitive closure  ",
