.TH load 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
load - load saved variable
.SH CALLING SEQUENCE
.nf
load('file-name')
.fi
.SH DESCRIPTION
loads the variables saved in file \fV'file-name'\fR and 
\fVload('file-name',x,y,...,z)\fR loads only variables \fVx,y,...,z\fR
of file \fV'file-name'\fR.
.SH SEE ALSO
save

