.TH bezout 8 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an 
.SH NAME
bezout - Bezout equation for polynomials
.SH CALLING SEQUENCE
.nf
[gcd,U]=bezout(p1,p2) 
.fi
.SH PARAMETERS
.TP 10 
p1, p2
: two real polynomials
.SH DESCRIPTION
.Vb [gcd,U]=bezout(p1,p2)
computes GCD \fVgcd\fR of \fVp1\fR and \fVp2\fR and in addition a (2x2) 
unimodular matrix \fVU\fR such that:
.LP
\fV[p1,p2]*U = [gcd,0]\fR
.LP
The lcm of \fVp1\fR and \fVp2\fR is given by:
.LP
\fVp1*U(1,2)\fR (or \fV-p2*U(2,2)\fR)
.SH SEE ALSO 
poly, roots, simpl, cleanp, lcm


