"  arma   - Scilab arma library ",
"  armac   - Scilab description of an armax process ",
"  armap   - display of armax equations ",
"  armax   - armax identification  ",
"  armax1   - armax identification ",
"  arsimul   - armax simulation  ",
"  arspec   - Spectral power estimation  ",
"  exar1   - armax identification example  ",
"  exar2   - armax identification example  ",
"  exar3   - armax identification example  ",
"  gbruit   - noise generation  ",
"  narsimul   - armax simulation ( using rtitr)  ",
"  odedi   - test of ode  ",
"  prbs_a   - pseudo random binary sequences generation  ",
"  reglin   - Linear regression  ",
"  vp   - ?  ",
