"  colnew   - boundary value problems for ODE ",
"  dassl   - differential algebraic equation ",
"  fsolve   - find a zero of a system of n nonlinear functions ",
"  impl   - differential algebraic equation ",
"  intc   - Cauchy integral ",
"  intg   - definite integral ",
"  intl   - Cauchy integral ",
"  karmarkar   - karmarkar (test program) ",
"  linpro   - linear programming solver ",
"  nemirov - Nemirovskii   - Nesterov's program ",
"  ode   - ordinary differential equation solver ",
"  optim   - non-linear optimization routine ",
"  quapro   - linear quadratic programming solver ",
