.TH dispfiles 1 "may 2000" "Scilab Group" "Scilab Function"
.so ../sci.an
.SH NAME
dispfile - display opened files properties
.SH CALLING SEQUENCE
.nf
dispfiles([units])
.fi
.SH PARAMETERS
.TP 7
units 
: a vector of numbers, the file's logical units. By default all opened
files.
.SH DESCRIPTION
dispfiles displays properties of currently opened files.
.SH EXAMPLE
.nf
dispfiles()
.fi
.SH SEE ALSO
file, mopen
.SH AUTHOR
S. Steer
