.TH getio 1 "december 2000" "Scilab Group" "Scilab Function"
.so ../sci.an
.SH NAME
getio - get Scilab input/output logical units
.SH CALLING SEQUENCE
.nf
ios=getio()
.fi 
.SH PARAMETERS
.TP 3
ios 
: a vector [rio rte wio wte]
.RS
.TP 4
rio
: current logical unit for reading instructions
.TP
rte
: logical unit assigned for input in main scilab window
.TP
wio
: logical unit relative to the diary file if any. wio=0 stands for no
diary file opened
.TP
wte
: logical unit assigned for output in main scilab window
.RE
.SH DESCRIPTION
\fVgetio\fR returns logical units assigned for main scilab input and output
.SH SEE ALSO
%io, file, exec


