.TH mputl 1 "April 2000" "Scilab Group" "Scilab Function"
.so ../sci.an
.SH NAME
mputl - writes strings in an ascii file
.SH CALLING SEQUENCE
.nf
mputl(txt [,file_desc]) 
.fi
.SH PARAMETERS
.TP 10
file_desc
:a character string giving the file name or a logical unit returned by
mopen. If omitted lines are written in the last file opened by mopen.
.TP
txt 
: a vector of strings.
.SH DESCRIPTION
\fVmputl\fR function allows to write a vector of strings as a sequence
of lines in an ascii file. 
.SH SEE ALSO
mputl, mclose,  mfprintf, mput, mputstr, mopen, write
.SH AUTHOR
S. Steer
