.TH isdef 3 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
isdef - check variable  existence
.SH CALLING SEQUENCE
.nf
isdef('var-name')
.fi
.SH DESCRIPTION
returns \fV%T\fR if the variable \fV'var-name'\fR exists 
and \fV%F\fR otherwise.
.SH SEE ALSO
exists, whereis, type, typeof