.TH sqroot 2 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an 
.SH NAME
sqroot - square root
.SH CALLING SEQUENCE
.nf
sqroot(X)
.fi
.SH PARAMETERS
.TP
X 
: symmetric non negative definite real or complex matrix
.SH DESCRIPTION
.Vb W=sqroot(X) 
returns the square root of \fVX\fR (uses SVD).
.SH SEE ALSO 
sqrt


