.TH CLKOUT_f 5 "Janvier 1996" "Scilab Group" "Scicos Block"
.so man1/sci.an
.SH NAME
CLKOUT - Scicos Super Block event output port
.SH DESCRIPTION
This block must only be used inside Scicos Super Blocks to represent
an event output port. 
.LP
In a Super_Block, the event output ports must be numbered from 1 to the
number of event output ports.
.SH DIALOG PARAMETERS
.TP 15
Output name
: A string defining the block label. This label is placed under
the block.
.TP
Port number
: an integer giving the port number.
.SH SEE ALSO
IN_f OUT_f CLKIN_f

