.TH CLOCK_f 5 "Janvier 1996" "Scilab Group" "Scicos Block"
.so man1/sci.an
.SH NAME
CLOCK - Scicos event clock
.SH DESCRIPTION
This block is a Super Block constructed by feeding back the output
of an event delay block into its input event port. The unique
output of this block generates a regular train of events.
.SH DIALOG PARAMETERS
.TP
Period
: scalar. One over the frequency of the clock. Period is the time that
separates two output events.
.SH SEE ALSO
EVTDLY_f







