.TH CLR_f 5 "Janvier 1996" "Scilab Group" "Scicos Block"
.so man1/sci.an
.SH NAME
CLR - Scicos continuous-time linear system (transfer function)
.SH DESCRIPTION
This block realizes a SISO linear system represented by its rational
transfer function (in the symbolic variable s).
The rational function must be proper.
.SH DIALOG PARAMETERS
.TP 20
Block label
: A string defining the block label. This label is written under
the block. 
.TP
Numerator
: a polynomial in s.
.TP
Denomiator
: a polynomial in s.
.SH SEE ALSO
CLSS_f INTEGRAL_f





