.TH CLSS_f 5 "Janvier 1996" "Scilab Group" "Scicos Block"
.so man1/sci.an
.SH NAME
CLSS - Scicos continuous-time linear state-space system
.SH DESCRIPTION
This block realizes a continuous-time linear state-space system.
The system is defined by the (A,B,C,D) matrices and the initial
state x0. The dimensions must be compatible.
.SH DIALOG PARAMETERS
.TP 20
Block label
: A string defining the block label. This label is written under
the block. 
.TP
A
: square matrix. The A matrix
.TP
B
: the B matrix
.TP
C
: the C matrix
.TP
D
: the D matrix
.TP
x0
: vector. The initial state of the system.
.SH SEE ALSO
CLR_f INTEGRAL_f





