.TH IFTHEL_f 5 "Janvier 1996" "Scilab Group" "Scicos Block"
.so man1/sci.an
.SH NAME
IFTHEL - Scicos if then else block
.SH DIALOG PARAMETERS
.TP 15
Block label
: string. The block label is placed under the block.
.SH DESCRIPTION
One event is generated on one of the output event ports when an
input event arrives. Depending on the sign of the regular input, 
the event is generated on the first or second output.








