.TH OUT_f 5 "Janvier 1996" "Scilab Group" "Scicos Block"
.so man1/sci.an
.SH NAME
OUT - Scicos Super Block regular output port
.SH DESCRIPTION
This block must only be used inside Scicos Super Blocks to represent
a regular output port. 
.LP
In a Super Block, regular output ports must be numbered from 1 to the
number of regular output ports.
.SH DIALOG PARAMETERS
.TP 15
Output name
: A string defining the block label. This label is placed under
the block.
.TP
Port number
: an integer giving the port number.
.SH SEE ALSO
CLKIN_f IN_f CLKOUT_f
