.TH INTEGRAL_f 5 "Janvier 1996" "Scilab Group" "Scicos Block"
.so man1/sci.an
.SH NAME
INTEGRAL - Scicos simple integrator
.SH DESCRIPTION
This block is an integrator. The output is the integral of the input.
.SH DIALOG PARAMETERS
.TP 15
Block label
: A string defining the block label. This label is placed under
the block.
.TP
Initial state
: a scalar. The initial condition of the integrator.
.SH SEE ALSO
CLSS_f CLR_f







