.TH REGISTER_f 5 "Janvier 1996" "Scilab Group" "Scicos Block"
.so man1/sci.an
.SH NAME
REGISTER - Scicos shift register block
.SH DESCRIPTION
This block realizes a shift register. At every input event, the
register is shifted one step.
.SH DIALOG PARAMETERS
.TP 20
Block label
: A string defining the block label. This label is written under
the block. 
.TP
Initial condition
: a column vector. It contains the initial state of the register.
.SH SEE ALSO
DLSS_f DLR_f







