.TH SAT_f 5 "Janvier 1996" "Scilab Group" "Scicos Block"
.so man1/sci.an
.SH NAME
SAT - Scicos Saturation block
.SH DESCRIPTION
This block realizes the non-linear function: saturation.
.SH DIALOG PARAMETERS
.TP 15
Block label
: A string defining the block label. This label is placed under
the block.
.TP
Min
: a scalar. Lower saturation bound
.TP
Max
: a scalar. Upper saturation bound
.TP
Slope
: a scalar. The slope of the line going through the origin 
and describing the behavior of the function around zero.
.SH SEE ALSO
LOOKUP_f





