.TH TIME_f 5 "Janvier 1996" "Scilab Group" "Scicos Block"
.so man1/sci.an
.SH NAME
TIME - Scicos time generator
.SH DIALOG PARAMETERS
.TP 15
Block label
: A string defining the block label. This label is placed under
the block.
.SH DESCRIPTION
This block is a time generator. The unique regular output is the
current time.





