.TH TRASH_f 5 "Janvier 1996" "Scilab Group" "Scicos Block"
.so man1/sci.an
.SH NAME
TRASH - Scicos Trash block
.SH DIALOG PARAMETERS
.TP 15
Block label
: string. Label to be placed under the block.
.TP
Number of inputs
: integer. The number of regular inputs. There is always one event input.
.SH DESCRIPTION
This block does nothing. It simply allows to safely connect the ouputs
of other blocks which should be ignored. This happens mostly for event
outputs that should produce no action.








