.TH ZCROSS_f 5 "Janvier 1996" "Scilab Group" "Scicos Block"
.so man1/sci.an
.SH NAME
ZCROSS - Scicos zero crossing detector
.SH DESCRIPTION
An output event is generated when all inputs (if more than one)
cross zero simultaneously.
.SH DIALOG PARAMETERS
.TP 20
Block label
: A string defining the block label. This label is written under
the block. 
.TP
Number of inputs
: integer.
.SH SEE ALSO
POSTONEG_f ZCROSS_f GENERAL_f





