.TH adj2l 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME 
adj2l -  adjacency 
.SH CALLING SEQUENCE
.nf
[lp,ls] = adj2l(a)
.fi
.SH PARAMETERS
.TP 10
a
: adjacency matrix
.TP 10
lp,ls
: vectors of the adjacency description
.SH DESCRIPTION
adjacency description from the adjacency matrix
.SH SEE ALSO
l2adj
