.TH anshp 1 "April 1993" "Scilab Group" "Scilab Macro"
.so man1/sci.an
.SH NAME 
anshp - arc number shortest path  
.SH CALLING SEQUENCE
.nf
[p,np] = anshp(i,j,[g])
.fi
.SH PARAMETERS
.TP 4
i,j 
: integers, node numbers
.TP
g
: graph list, optional argument with default value \fVthe_g\fR
.TP
p
: row vector of arc numbers
.TP
np
: integer, length of vector p
.SH DESCRIPTION
\fVanshp\fR returns the shortest path \fVp\fR in arc numbers from 
node\fVi\fR to node \fVj\fR. \fVnp\fR is the nomber of arcs of this path.
.SH SEE ALSO
anpath, lshp, ns2p
