.TH compl2 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME 
compl2 -  from directed to undirected adjacency description 
.SH CALLING SEQUENCE
.nf
[la2,lp2,ls2] = compl2(la1,lp1,ls1,dir)
.fi
.SH PARAMETERS
.SH DESCRIPTION
computes the adjacency description for undirected graph from 
the adjacency description
.SH SEE ALSO
compla
