.TH gmaxflow 1 "April 1993" "Scilab Group" "Scilab Macro"
.so man1/sci.an
.SH NAME 
gmaxflow - global maximum flow  
.SH CALLING SEQUENCE
.nf
[v,f] = gmaxflow([g])
.fi
.SH PARAMETERS
.TP 2
g
: graph list, optional argument with default value \fVthe_g\fR
.TP
v
: integer, value of the flow on the return arc (sink,source)
.TP
f
: array of the flows on the arcs
.SH DESCRIPTION
\fVgmaxflow\fR returns the maximum flow from the source to the sink 
for the directed graph \fVg\fR with only one source and one sink .
.SH SEE ALSO
maxflow
