.TH isconnex 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME 
isconnex - connectivity test  
.SH CALLING SEQUENCE
.nf
[iscon] = isconnex([g])
.fi
.SH PARAMETERS
.TP 6
g
: graph list, optional argument with default value \fVthe_g\fR
.TP 
iscon
: integer
.SH DESCRIPTION
\fVisconnex\fR returns 1 if the graph \fVg\fR is connex and 0 otherwise.
.SH SEE ALSO
concomp, connex
