.TH makeund 1 "April 1993" "Scilab Group" "Scilab macro"
.so man1/sci.an
.SH NAME 
makeund -  from directed to undirected graph 
.SH CALLING SEQUENCE
.nf
[g1] = makeund([g])
.fi
.SH PARAMETERS
.TP 3
g
: graph list, optional argument with default value \fVthe_g\fR
.TP
g1
: graph list
.SH DESCRIPTION
\fVmakeund\fR returns the undirected graph \fVg1\fR corresponding to 
the graph \fVg\fR.
