.TH fplot3d1 2 "April 1993" "Scilab Group" "Scilab Function" 
.so ../sci.an
.SH NAME
fplot3d1 - gray level plotting of a surface 
.SH CALLING SEQUENCE
.nf
fplot3d1(xr,yr,f [,theta,alpha,leg,flag,ebox])
.fi
.SH PARAMETERS
( )
: see \fVfplot3d\fR
.SH DESCRIPTION
This routines plots a surface defined by an external \fVf\fR.
the value of \fVf\fR on the grid defined by \fVxr.yr\fR is first computed 
using \fVfeval\fR, then control is passed to the primitive \fVplot3d1\fR.

Enter the command \fVfplot3d1()\fR to see a demo.
.SH AUTHOR
J.Ph.C.





