.TH xdel 2 "April 1993" "Scilab Group" "Scilab Function"
.so ../sci.an
.SH NAME
xdel - delete a graphic window
.SH CALLING SEQUENCE
.nf
xdel([win-num]) 
.fi
.SH DESCRIPTION
Deletes the graphic window \fVwin-num\fR if the name is specified 
or the current graphic window otherwise
.SH AUTHOR
J.Ph.C.


