.TH invsyslin 1 "April 1993" "Scilab Group" "Scilab Function"
.so ../sci.an 
.SH NAME
invsyslin - system inversion
.SH CALLING SEQUENCE
.nf
[sl2]=invsyslin(sl1) 
.fi
.SH PARAMETERS
.TP
sl1,sl2
: \fVsyslin\fR lists (linear systems in state space representation)
.SH DESCRIPTION
Utility function. Computes the state form of the inverse \fVsl2\fR of 
the linear system \fVsl1\fR (which is also given in state form). 
.LP
The \fVD\fR-matrix is supposed to be full rank. Old stuff used by 
\fVinv(S)\fR when \fVS\fR is a \fVsyslin\fR list.
.SH SEE ALSO
rowregul, inv
