.TH %asn 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
%asn - elliptic integral
.SH CALLING SEQUENCE
.nf
[y]=%asn(x,m)
.fi
.SH PARAMETERS
.TP
x
: upper limit of integral (\fVx>0\fR) (can be a vector)
.TP
m
: parameter of integral (\fV0<m<1\fR)
.TP
y
: value of the integral
.SH DESCRIPTION
Calculates the elliptic integral
.IG	
.nf
 y = integral from 0 to x of [1/(((1-t*t)^(1/2))(1-m*t*t)^(1/2))]
.fi
.FI
.LA $$ K= \int_0^x  {dt \over [(1-t^2)(1-m t^2)]^{1/2}} $$
If \fVx\fR is a vector, \fVy\fR is a vector of same dimension as \fVx\fR.
.SH AUTHOR
F. D.
