.TH chepol 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
chepol - Chebychev polynomial
.SH CALLING SEQUENCE
.nf
[Tn]=chepol(n,var)
.fi
.SH PARAMETERS
.TP
n
: integer : polynomial order
.TP
var
: string : polynomial variable
.TP
Tn
: polynomial in the variable \fVvar\fR
.SH DESCRIPTION
Recursive implementation of Chebychev polynomial
.SH AUTHOR
F. D.
