.TH dft 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
dft - discrete fourier transform
.SH CALLING SEQUENCE
.nf
[xf]=dft(x,flag);
.fi
.SH PARAMETERS
.TP 10
x
: input vector
.TP
flag
: indicates dft or idft
.TP
xf
: output vector
.SH DESCRIPTION
Function which computes dft of vector \fVx\fR
.SH SEE ALSO
fft
.SH AUTHOR
C. B.
