.TH det 2 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
det  - determinant
.SH CALLING SEQUENCE
.nf
det(X)
.fi
.SH PARAMETERS
.TP
X 
: real or complex square matrix, polynomial or rational matrix.
.SH DESCRIPTION
\fVdet(X)\fR is the determinant of the square matrix \fVX\fR.
.LP
For polynomial matrix \fVdet(X)\fR is equivalent to \fVdeterm(X)\fR.
.LP
For rational matrices \fVdet(X)\fR is equivalent to \fVdetr(X)\fR.
.SH SEE ALSO
detr, determ



