.TH part 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
part - extraction of strings
.SH CALLING SEQUENCE
.nf
[c]=part(mp,v)
.fi
.SH PARAMETERS
.TP 10
mp,c
: string matrices
.TP 10
v
: integer vector of indices
.SH DESCRIPTION
returns the matrix of character strings
of \fVmp\fR made of characters in the \fVv\fR vector.
.SH SEE ALSO
string

