SHELL = /bin/sh

SUBDIRS = gengraph src

all::
	@case '${MFLAGS}' in *[ik]*) set +e;; esac; \
	for i in $(SUBDIRS) ;\
	do \
		(cd $$i ; echo "making all in xmetanet/$$i..."; \
		$(MAKE) $(MFLAGS) all); \
	done

world: all

distclean::
	@case '${MFLAGS}' in *[ik]*) set +e;; esac; \
	for i in $(SUBDIRS) ;\
	do \
		(cd $$i ; echo "making distclean in xmetanet/$$i..."; \
		$(MAKE) $(MFLAGS)  distclean); \
	done

clean::
	@case '${MFLAGS}' in *[ik]*) set +e;; esac; \
	for i in $(SUBDIRS) ;\
	do \
		(cd $$i ; echo "making clean in xmetanet/$$i..."; \
		$(MAKE) $(MFLAGS) clean); \
	done
