.TH round G "April 1993" "Scilab Group" "Scilab Function"
.so ../sci.an
.SH NAME
round - rounding
.SH CALLING SEQUENCE
.nf
y=round(x)
.fi
.SH PARAMETERS
.TP 10
x 
: real or complex matrix
.TP 10
y
: integer or complex (with integer real and imag) matrix
.SH DESCRIPTION
\fVround(x)\fR rounds the elements of \fVx\fR to the nearest integers.
.SH EXAMPLE
.nf
round([1.9 -2.5])-[2,-3]
round(1.6+2.1*%i)-(2+2*%i)
round(-%inf)
x=rand()*10^20;round(x)-x
.fi
.SH SEE ALSO
int, floor, ceil
