.TH frep2tf 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an 
.SH NAME
frep2tf - frequency response to  transfer function
.SH CALLING SEQUENCE
.nf
[h [,err]]=frep2tf(frq,repf,dg) 
.fi
.SH PARAMETERS
.TP 10
frq   
: vector of frequencies
.TP
repf  
: vector of frequency response
.TP
dg    
: degree of linear system
.TP
h     
: SISO transfer function 
.TP
err   
: error \fVnorm([ n(2i*pi*frq) - rep.*d(2i*pi*frq)],'fro')\fR
.SH DESCRIPTION
Frequency response to  transfer function conversion. The order of \fVh\fR
is a priori given in \fVdg\fR which must be provided.



