.TH LTITR G "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an 
.SH NAME
ltitr - discrete time response (state space)
.SH CALLING SEQUENCE
.nf
[X]=ltitr(A,B,U,[x0]) 
[xf,X]=ltitr(A,B,U,[x0])
.fi
.SH PARAMETERS
.TP 10
A,B 
: real  matrices of appropriate dimensions
.TP
U,X   
: real  matrices 
.TP
x0,xf  
: real vectors (default value=0 for \fVx0\fR))         
.SH DESCRIPTION
calculates the time response of the discrete time system
.nf
         x[t+1] = Ax[t] + Bu[t].
.fi
The inputs \fVui\fR's are the columns of the \fVU\fR matrix
.nf
        U=[u0,u1,...,un];
.fi
\fVx0\fR is the vector of initial state (default value : 0) ;
.LP
\fVX\fR is the matrix of outputs (same number of columns as \fVU\fR).
.LP
.nf
        X=[x0,x1,x2,...,xn] 
.fi    
\fVxf\fR is the vector of final state \fVxf=X[n+1]\fR
.SH SEE ALSO 
rtitr, flts.

