.TH tf2ss 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an 
.SH NAME
tf2ss - transfer to state-space
.SH CALLING SEQUENCE
.nf
[sl]=tf2ss(h)
.fi
.SH PARAMETERS
.TP
h
: rational matrix
.TP
sl
: linear system (\fVsyslin\fR list \fVsl=[A,B,C,D(s)]\fR)
.SH DESCRIPTION
transfer to state-space conversion: 
.LP
\fVh=C*(s*eye-A)^-1*B+D(s)\fR
.SH SEE ALSO
ss2tf, tf2des, des2tf

