mode(-1)
//to Check all the demos
 funcprot(0)
clearfun('x_message')
clearfun('x_dialog')
clearfun('x_mdialog')
clearfun('x_choose')
clearfun('mode')
clearfun('xclick')
deff('[]=mode(x)','x=x')
deff('[]=halt(  )',' ')
getf('SCI/macros/util/x_matrix.sci','c')
getf('SCI/macros/util/getvalue.sci')
names=read('SCI/macros/scicos/names',-1,1,'(a)')
for k=1:size(names,'r')
  getf('SCI/macros/scicos/'+names(k)+'.sci')
end
lines(0)
clearfun('lines')
deff('x=lines(x)','x=0 ')
getf('SCI/tests/dialogs.sci','c')
I=file('open','SCI/tests/demos.dialogs','old')
O=file('open','/dev/null','unknown')
%IO=[I,O]
lines(0)
exec('SCI/demos/alldems.dem')
file('close',I)
file('close',O)

