.TH CLKINV_f 5 "Janvier 1996" "Scilab Group" "Scicos Block"
.so ../sci.an
.SH NAME
CLKINV_f - Scicos Super Block event input port
.SH DESCRIPTION
This block must only be used inside Scicos Super Blocks to represent
an event input port. 
.LP
In a Super Block, the event input ports must be numbered from 1 to the
number of event input ports.
.SH DIALOGUE PARAMETERS
.TP 15
Port number
: an integer defining the port number.
.SH SEE ALSO
IN_f, OUT_f, CLKOUTV_f
