.TH DEMUX_f 5 "Janvier 1997" "Scilab Group" "Scicos Block"
.so ../sci.an
.SH NAME
DEMUX_f - Scicos demultiplexer block
.SH DIALOGUE PARAMETERS
.TP 25
number of output ports
:
positive integer less than or equal to 8.
.SH DESCRIPTION
Given a vector valued input this block splits inputs over vector
valued outputs. So \fVu=[y1;y2....;yn]\fR, where \fVyi\fR are numbered
from top to bottom. Input and Output port sizes are determined by the
context.
.SH SEE ALSO
MUX_f
