.TH GENSIN_f 5 "Janvier 1996" "Scilab Group" "Scicos Block"
.so ../sci.an
.SH NAME
GENSIN_f - Scicos sinusoid generator
.SH DESCRIPTION
This block is a sine wave generator: M*sin(F*t+P)
.SH DIALOGUE PARAMETERS
.TP 15
Magnitude
: a scalar. The magnitude M.
.TP
Frequency
: a scalar. The frequency F.
.TP
Phase
: a scalar. The phase P.
.SH SEE ALSO
GENSQR_f, RAND_f, SAWTOOTH_f






