.TH scicos 5 "Janvier 1996" "Scilab Group" "Scilab function"
.so ../sci.an
.SH NAME
scicos - Block diagram editor and GUI for the hybrid simulator scicosim
.SH CALLING SEQUENCE
.nf
sys=scicos()
sys=scicos(sys,[menus])
sys=scicos(file,[menus])
.fi
.SH PARAMETERS
.TP
sys
: a Scicos data structure
.TP
file
: a character string. The path of a file containing the  image
of a Scicos data structure. These files may have \fV.cos\fR or
\fV.cosf\fR extensions.
.TP
menus
: a vector of character strings. It allows to select some of the
Scicos menus. If \fVmenus==[]\fR  Scicos draws the diagram and the
contents of each super blocks in separate windows without menu
bar. This option is useful to print diagrams.

.SH DESCRIPTION
Scicos is a visual editor for constructing models of hybrid dynamical
systems. Invoking Scicos with no argument opens up an empty Scicos
window. Models can then be assembled, loaded, saved, compiled,
simulated, using GUI of Scicos. The input and ouput arguments are only
useful for debugging purposes. Scicos serves as an interface to the
various block diagram compilers and the hybrid simulator scicosim.

.SH SEE ALSO
scicosim, scicos_main, scicos_menus 
      







