.TH CONST_f 5 "Janvier 1996" "Scilab Group" "Scicos Block"
.so man1/sci.an
.SH NAME
CONST - Scicos constant value(s) generator
.SH DIALOG PARAMETERS
.TP 15
Block label
: A string defining the block label. This label is placed under
the block.
.TP
constants
: a real vector. The vector size gives the number of output
ports. The value \fVconstants(i)\fR is assigned to the ith port.
Note that output ports are numbered from top to bottom.
.SH DESCRIPTION
This block is a constant value(s) generator.




