.TH COSBLK_f 5 "Janvier 1996" "Scilab Group" "Scicos Block"
.so man1/sci.an
.SH NAME
COSBLK - Scicos cosine block
.SH DIALOG PARAMETERS
.TP 20
Block label
: A string defining the block label. This label is written under
the block. 
.TP
number of inputs
: a scalar. This fixes the number of inputs and outputs.
.SH DESCRIPTION
This block realizes vector cosine operation.








