.TH SOM_f 5 "Janvier 1996" "Scilab Group" "Scicos Block"
.so man1/sci.an
.SH NAME
SOM - Scicos addition block
.SH DESCRIPTION
This block is a sum. The output is the sum of the inputs.
.SH DIALOG PARAMETERS
.TP 
Number of inputs
: a scalar. Safe to leave at three even if you connect less inputs.
More than 3 is not allowed. Use Gain for more inputs.
.TP
Input signs
: a (1x3) vector of +1 and -1. If -1, the corresponding input is
multipled by -1 before addition.
.SH SEE ALSO
GAIN_f







