.TH fullrfk 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
fullrfk - full rank factorization of A^k
.SH CALLING SEQUENCE
.nf
[Bk,Ck]=fullrfk(A,k)
.fi
.SH PARAMETERS
.TP 10
A
: real or complex matrix
.TP
k
: integer
.TP
Bk,Ck
: real or complex matrices
.SH DESCRIPTION
This macro computes the full rank factorization of \fVA^k\fR i.e.
\fVBk*Ck=A^k\fR where \fVBk\fR is full column rank and \fVCk\fR full row rank.
One has range(\fVBk\fR)=range(\fVA^k\fR) and ker(\fVCk\fR)=ker(\fVA^k\fR).
.LP
For \fVk=1\fR, \fVfullrfk\fR is equivalent to \fVfullrf\fR.
.SH SEE ALSO
fullrf, range
.SH AUTHOR
F.D (1990)

