.TH readc_ 3 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
readc_ - read a character string
.SH CALLING SEQUENCE
.nf
[c]=readc_(unit)
[c]=readc_()
.fi
.SH DESCRIPTION
\fVreadc_\fR reads a character string 
This macro allows one to interrupt an exec file without \fVpause\fR;
the exec file stops until carriage return is made.
.SH SEE ALSO
read


