.TH x_choose 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
x_choose - interactive Xwindow choice
.SH CALLING SEQUENCE
.nf
[num]=x_choose(items,title) 
.fi
.SH DESCRIPTION
Returns in \fVnum\fR the number of the chosen item.
.SH EXAMPLE
.nf
n=x_choose(['item1';'item2';'item3'],'title')
.fi
