"  augment   - augmented plant ",
"  bstap   - hankel approximant ",
"  ccontrg   - central H-infinity controller ",
"  colinout   - inner-outer factorization ",
"  copfac   - right coprime factorization ",
"  dcf   - double coprime factorization ",
"  des2ss   - descriptor to state-space ",
"  dtsi   - stable anti-stable decomposition ",
"  fourplan   - augmented plant to four plants ",
"  fspecg   - stable factorization ",
"  fstabst   - Youla's parametrization ",
"  gamitg   - H-infinity gamma iterations ",
"  gcare   - control Riccati equation ",
"  gfare   - filter Riccati equation ",
"  gtild   - tilde operation ",
"  h2norm   - H2 norm ",
"  h_cl   - closed loop matrix ",
"  h_inf   - H-infinity (central) controller ",
"  H_inf_st   - static H_infinity problem  ",
"  H_norm   - H-infinity norm ",
"  hankelsv   - Hankel singular values ",
"  lcf   - normalized coprime factorization ",
"  leqr   - H-infinity LQ gain (full state) ",
"  lft   - linear fractional transformation ",
"  linf   - infinity norm ",
"  linfn   - infinity norm ",
"  lqg_ltr   - LQG with loop transform recovery ",
"  Macglov   - Mac Farlane Glover problem ",
"  musolve   - structured singular value, mu, ssv ",
"  nehari   - Nehari approximant ",
"  parrot   - Parrot's problem ",
"  ric_desc   - Riccati equation ",
"  riccati   - Riccati equation ",
"  rowinout   - inner-outer factorization ",
"  sensi   - sensitivity functions ",
"  tf2des   - transfer function to descriptor ",
