"  balanc   - matrix or pencil balancing ",
"  bdiag   - block diagonalization. ",
"  chol   - Cholesky factorization ",
"  coff   - resolvent (cofactor method) ",
"  colcomp   - column compression, kernel, nullspace ",
"  cond   - condition number ",
"  det    - determinant ",
"  epsfin   - reduced pencil ",
"  exp   - exponential, matrix exponential ",
"  fineta   - reduced pencil ",
"  fullrf   - full rank factorization ",
"  fullrfk   - full rank factorization of A^k ",
"  givens   - Givens transformation ",
"  glever   - inverse of matrix pencil  ",
"  gschur   - generalized Schur form (matrix pencils). ",
"  gspec   - eigenvalues of matrix pencil ",
"  hess   - Hessenberg form ",
"  im_inv   - inverse image ",
"  inv   - matrix inverse ",
"  kroneck   - Kronecker form ",
"  leverrier   - Leverrier's algorithm ",
"  lu   - LU factors of Gaussian elimination ",
"  ludel   - utility function used with lufact ",
"  lufact   - sparse lu factorization ",
"  lusolve   - sparse linear system solver ",
"  lyap    - Lyapunov equation ",
"  nlev   - Leverrier's algorithm  ",
"  orth   - orthogonal basis ",
"  pbig   - eigen-projection  ",
"  pencan   - canonical form of matrix pencil ",
"  penlaur   - Laurent coefficients of matrix pencil ",
"  pinv   - pseudoinverse ",
"  polar   - polar form ",
"  proj   - projection ",
"  projspec   - spectral operators  ",
"  psmall   - spectral projection ",
"  qr   - QR decomposition ",
"  quaskro   - quasi-Kronecker form ",
"  range   - range (span) of A^k ",
"  rank   - rank ",
"  rcond   -  inverse condition number ",
"  rowcomp   - row compression, range ",
"  rowshuff   - shuffle algorithm ",
"  schur   - [ordered] Schur decomposition ",
"  spaninter   - subspace intersection ",
"  spanplus   - sum of subspaces ",
"  spantwo   - sum and intersection of subspaces ",
"  spec   - eigenvalues ",
"  sqroot   - square root ",
"  sva   - singular value approximation ",
"  svd    -  singular value decomposition ",
"  sylv   - Sylvester equation. ",
