.TH backslash 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
\\ - left matrix division
.SH CALLING SEQUENCE
.nf
x=A\b
.fi
.SH DESCRIPTION
Left matrix division. \fVx=A\\b\fR is the solution of \fVA*x=b\fR.  
The least square solution is given if the system is singular.
.LP
\fVA.\\b\fR  is the matrix with \fV(i,j)\fR entry \fVa(i,j)\\b(i,j)\fR.
.SH SEE ALSO
/, percent

