.TH int 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
int - integer part
.SH CALLING SEQUENCE
.nf
[y]=int(X)
.fi
.SH PARAMETERS
.TP
X 
: real matrix
.TP
y
: integer matrix
.SH DESCRIPTION
\fVint(X)\fR returns the integer part of the real matrix \fVX\fR.
.SH SEE ALSO
round, floor, ceil

