.TH  keyborad 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
keyboard - keyborad commands
.SH DESCRIPTION
The following keyboard commands are available:
.LP
\fV ^D \fR (\fVControl-D\fR) \fV : \fR deletes the current character
.LP
\fV ^P \fR (\fVControl-P\fR) \fV : \fR calls back the preceding command
.LP
\fV ^N \fR (\fVControl-N\fR) \fV : \fR go to next command line
.LP
\fV ^A \fR (\fVControl-A\fR) \fV : \fR moves the cursor to the beginning of command line.
.LP
\fV ^B \fR (\fVControl-B\fR) \fV : \fR backspace, moves the cursor one caracter
to the left
.LP
\fV ^F \fR (\fVControl-F\fR) \fV : \fR forwards, moves the cursor one caracter
to the right
.LP
\fV ^K \fR (\fVControl-K\fR) \fV : \fR kills command line from cursor to the end.
.LP
\fV ^Y \fR (\fVControl-Y\fR) \fV : \fR yank, retrieves killed line.
.LP
\fV !beg \fR \fV : \fR looks for last command line which begins by \fVbeg\fR.
.LP
\fV ^C \fR (\fVControl-C\fR) \fV : interrupts Scilab and pause after
carriage return. (Only macros can be interrupted).
Clicking on the stop button enters a \fV ^C \fR.




