SHELL = /bin/sh

SCIDIR=../..
SCIDIR1=..\..

include ../../Makefile.incl

.SUFFIXES: .sci .bin $(SUFFIXES)

NAME = soundlib
NAM = sound

MACROS = analyze.sci mapsound.sci soundsec.sci

include ../Make.lib
