SHELL = /bin/sh

SCIDIR=../..
include ../../Makefile.incl

.SUFFIXES: .sci .bin $(SUFFIXES)

NAME = armalib
NAM = arma

MACROS = armap.sci armax.sci armax1.sci arsimul.sci arspec.sci \
	epred.sci exar1.sci exar2.sci \
	exar3.sci gbruit.sci narsimul.sci odedi.sci prbs_a.sci  \
	vpmacr.sci armac.sci reglin.sci acf.sci sdiff.sci

include ../Make.lib
