.TH srkf 1 "April 1993" "Scilab Group" "Scilab Function"
.so ../sci.an
.SH NAME
srkf - square root Kalman filter
.SH CALLING SEQUENCE
.nf
[x1,p1]=srkf(y,x0,p0,f,h,q,r)
.fi
.SH PARAMETERS
.TP 10
f, h
: current system matrices
.TP
q, r
: covariance matrices of dynamics and observation noise
.TP
x0, p0
: state estimate and error variance at t=0 based on data up to t=-1
.TP
y
: current observation Output from the function is
.TP
x1, p1
: updated estimate and error covariance at t=1 based on data up to t=0
.SH DESCRIPTION
square root Kalman filter algorithm
.SH AUTHOR
C. B.
