.TH getlinestyle 2 "April 1993" "Scilab Group" "Scilab Function"
.SH NAME
getlinestyle - dialog to select linestyle
.SH CALLING SEQUENCE
.nf
k=getlinestyle()
.fi
.SH PARAMETERS
.TP
k
: integer, selected linestyle  or [] if the "Cancel" button has been clicked.
.SH DESCRIPTION
\fVgetlinestyle\fR opens a graphic window to select a line style.
Example: \fVk=getlinestyle()\fR \fVplot2d(1:10,10,style=k)\fR.
.SH SEE ALSO
xset
