.TH getmark 2 "April 1993" "Scilab Group" "Scilab Function"
.SH NAME
getmark - dialog to select mark (symbol)
.SH CALLING SEQUENCE
.nf
[mark,mrkSize]=getmark()
.fi
.SH PARAMETERS
.TP
mark
: integer, the number of the selected mark
.TP
mrkSize
: integer, the size of the selected mark
.SH DESCRIPTION
\fVgetmark\fR opens a graphic window to select a mark (symbol).
Usage: \fV[mark,mrkSize]=getmark()\fR. 
\fVxset("mark size",mrkSize)\fR. \fVplot2d(x,y,style=mark)\fR.
.SH SEE ALSO
xset, getfont
