.TH plot2d3 2 "April 1993" "Scilab Group" "Scilab Function"
.so ../sci.an
.SH NAME
plot2d3 - 2D plot (vertical bars)
.SH CALLING SEQUENCE
.nf
plot2d3([logflags,] x,y,[style,strf,leg,rect,nax])
plot232(y)
plot2d3(x,y <,opt_args>)
.fi
.SH PARAMETERS
[ ]
: see \fVplot2d\fR  for a description of parameters.
.SH DESCRIPTION
\fVplot2d3\fR is the same as \fVplot2d\fR but curves are plotted using 
vertical bars.

By default, successive plots are superposed. To clear the previous plot, 
use \fVxbasc()\fR.

Enter the command \fVplot2d3()\fR to see a demo.
.SH EXAMPLE
.nf
// compare the following with plot2d1
x=[0:0.1:2*%pi]';
plot2d3(x,[sin(x) sin(2*x) sin(3*x)])
.fi
.SH SEE ALSO
plot2d, plot2d2, plot2d4, xbasc, xset
.SH AUTHOR
J.Ph.C.
