
all	: Sin2.ps Sin4.ps Sin6.ps
	latex all


clean	:
	\rm Sin*.ps Sin*.tex 



Sin2.ps: BasSin.ps 
	Blatexprs Sin2 BasSin.ps BasSin.ps 

Sin4.ps: BasSin.ps 
	Blatexprs Sin4 BasSin.ps BasSin.ps  BasSin.ps BasSin.ps 

Sin6.ps: BasSin.ps 
	Blatexprs Sin6 BasSin.ps BasSin.ps  BasSin.ps BasSin.ps  BasSin.ps BasSin.ps 






