.TH besselj 3 "September 1997" "Scilab Group" "Scilab Function"
.so ../sci.an
.SH NAME
besselj -  Modified J sub ALPHA Bessel functions of the first kind.
.SH CALLING SEQUENCE
.nf
 y = besselj(alpha,x)
.fi
.SH PARAMETERS
.TP
x
: real vector with non negative entries
.TP
alpha
: real vector with non negative entries regularly spaced with
increment equal to one \fValpha=alpha0+(n1:n2)\fR
.TP
ice
: integer flag, with default value 1
.SH DESCRIPTION

\fVbesselj(alpha,x)\fR computes J sub ALPHA modified Bessel functions of the
first kind, for real, non-negative order \fValpha\fR 
and argument \fVx\fR.  \fValpha\fR  and \fVx\fR may be vectors.
The output is \fVm\fR-by-\fVn\fR with \fVm = size(x,'*')\fR,
\fVn = size(alpha,'*')\fR whose \fV(i,j)\fR entry is
\fVbesselj(alpha(j),x(i))\fR.


.SH EXAMPLE
.nf
besselj(0.5:3,1:4)

.fi
.SH SEE ALSO
besseli, besselk
