.TH imag G "April 1993" "Scilab Group" "Scilab Function"
.so ../sci.an
.SH NAME
imag - imaginary part
.SH CALLING SEQUENCE
.nf
[y]=imag(x)
.fi
.SH PARAMETERS
.TP
x
: real or complex vector or matrix.
.TP
y
: real vector or matrix.
.SH DESCRIPTION
\fVimag(x)\fR is the imaginary part of \fVx\fR. (See \fV %i\fR to enter complex numbers).
.SH SEE ALSO
real
