.TH mu2lin 1 "April 1993" "Scilab Group" "Scilab Function"
.so ../sci.an
.SH NAME
mu2lin - mu-law encoding to linear signal
.SH CALLING SEQUENCE
.nf
mu=lin2mu(y)
.fi
.SH PARAMETERS
.TP
y
: real vector
.TP
mu
: real vector
.SH DESCRIPTION
Utility fct: \fVy=mu2lin(mu)\fR converts mu-law encoded 8-bit audio signals,
stored in the range 0 <= mu <= 255, to linear signal amplitude in 
the range -s < y < s where s = 32124/32768 ~= .9803.  
The input mu is often obtained using mget(...,'uc') to read 
byte-encoded audio files.   Translation of C program by Craig Reese: 
IDA/Supercomputing Research Center Joe Campbell: Department of Defense
.SH SEE ALSO
mu2lin




