.TH sound 1 "April 1993" "Scilab Group" "Scilab Function"
.so ../sci.an
.SH NAME
sound -  sound player facility
.SH CALLING SEQUENCE
.nf
sound(y)
sound(y,fs)
sound(y,fs,bits)
.fi
.SH PARAMETERS
.TP
y
: real vector
.TP
fs
: real number, sampling frequency
.TP
bits
: real number, number of bits (usually 8 or 16)
.SH DESCRIPTION
\fVsound(y,fs)\fR sends the signal in vector y (with sample frequency
fs) out to the speaker. Values in y are assumed to be in the 
range -1.0 <= y <= 1.0. Values outside that range are ugnored.  
Stereo sounds are played, on platforms that support it, when y is 
an N-by-2 matrix. 
\fVsound(y)\fR plays the sound at the default sample rate of 8192 Hz.
\fVsound(y,fs,nbits)\fR plays the sound using nbits bits/sample if
possible.  Most platforms support bits=8 or 16.
.SH SEE ALSO
playsnd





