.TH < 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
 < - lower
.SH DESCRIPTION
logical comparison symbol
.TP
\fV<>\fR means "different" (same as \fV~=\fR)
.TP
\fV<\fR means "lower than"
.TP
\fV>\fR means "larger than"
.TP
\fV<=\fR means lower than or equal to.
.TP
\fV>=\fR means larger than or equal to
.SH SEE ALSO
if 
