.TH round G "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
round - rounding
.SH CALLING SEQUENCE
.nf
[y]=round(x)
.fi
.SH PARAMETERS
.TP 10
x 
: real or complex matrix
.TP 10
y
: integer or complex (with integer real and imag) matrix
.SH CALLING SEQUENCE
\fVround(x)\fR rounds the elements of \fVx\fR to the nearest integers.
.SH SEE ALSO
int, floor, ceil
