.TH pol2tex 3 "April 1993" "Scilab Group" "Scilab Function"
.so ../sci.an
.SH NAME
pol2tex - convert polynomial  to TeX format
.SH CALLING SEQUENCE
.nf
[y]=pol2tex(x)
.fi
.SH PARAMETERS
.TP 10
x
: polynomial 
.TP 10
y
: list
.SH DESCRIPTION
Latex source code for the polynomial  \fVx\fR.
(For use with \fVtexprint\fR)
.SH EXAMPLE
.nf
s=poly(0,'s');
p=s^3+2*s-5;
pol2tex(p)
.fi
.SH SEE ALSO
texprint

