.TH  keyborad 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
keyboard - keyborad commands
.SH DESCRIPTION
Let \fVC-\fR stands for the control key. The following keyboard commands are available:
.TP
C-l  \fR clears the Scilab window
.TP
C-d 
deletes the current character
.TP
C-p 
calls back the preceding command
.TP
C-n 
go to next command line
.TP
C-a 
moves the cursor to the beginning of command line.
.TP
C-b 
backspace, moves the cursor one caracter to the left
.TP
C-f 
forwards, moves the cursor one caracter
to the right
.TP
C-k 
kills command line from cursor to the end.
.TP
C-y 
yank, retrieves killed line.
.TP
!beg
looks for last command line which begins by \fVbeg\fR.
.TP
C-c 
interrupts Scilab and pause after
carriage return. (Only functions can be interrupted).
Clicking on the stop button enters a \fVC-C\fR.
.SH SEE ALSO
pause, read, input




