making test in macros/algebre...
Processing file aff2ab.sci
Starting Compilation
Running Scilab
generating lib and names
Running Scilab
End of compilation
making test in macros/arma...
Processing file armax.sci
Processing file armax1.sci
Processing file arsimul.sci
Processing file noisegen.sci
Processing file narsimul.sci
Processing file prbs_a.sci
Processing file armac.sci
Processing file reglin.sci
Processing file acf.sci
Processing file sdiff.sci
Starting Compilation
Running Scilab
generating lib and names
Running Scilab
End of compilation
making test in macros/auto...
Processing file calfrq.sci
Processing file svplot.sci
Processing file abcd.sci
Processing file sm2ss.sci
Processing file sm2des.sci
Processing file arhnk.sci
Processing file balreal.sci
Processing file observer.sci
Processing file stabil.sci
Processing file canon.sci
Processing file cont_frm.sci
Processing file cont_mat.sci
Processing file contrss.sci
Processing file unobs.sci
Processing file csim.sci
Processing file ctr_gram.sci
Processing file cls2dls.sci
Processing file dscr.sci
Processing file dsimul.sci
Processing file dt_ility.sci
Processing file equil.sci
Processing file equil1.sci
Processing file flts.sci
Processing file frep2tf.sci
Processing file freson.sci
Processing file g_margin.sci
Processing file gfrancis.sci
Processing file imrep2ss.sci
Processing file invsyslin.sci
Processing file kpure.sci
Processing file krac2.sci
Processing file invrs.sci
Processing file lqe.sci
Processing file lqr.sci
Processing file markp2ss.sci
Processing file minreal.sci
Processing file minss.sci
Processing file obs_gram.sci
Processing file obsv_mat.sci
Processing file obsvss.sci
Processing file p_margin.sci
Processing file pfss.sci
Processing file phasemag.sci
Processing file projsl.sci
Processing file des2tf.sci
Processing file repfreq.sci
Processing file ss2tf.sci
Processing file ss2des.sci
Processing file ss2ss.sci
Processing file st_ility.sci
Processing file statgain.sci
Processing file lqg.sci
Processing file lqg2stan.sci
Processing file obscont.sci
Processing file tf2ss.sci
Processing file trzeros.sci
Processing file colregul.sci
Processing file rowregul.sci
Processing file time_id.sci
Processing file zeropen.sci
Processing file specfact.sci
Processing file abinv.sci
Processing file cainv.sci
Processing file dbphi.sci
Processing file bilin.sci
Processing file arl2.sci
Starting Compilation
Running Scilab
generating lib and names
Running Scilab
End of compilation
making test in macros/calpol...
Processing file cmndred.sci
Processing file coffg.sci
Processing file colcompr.sci
Processing file denom.sci
Processing file derivat.sci
Processing file determ.sci
Processing file detr.sci
Processing file diophant.sci
Processing file gcd.sci
Processing file hermit.sci
Processing file horner.sci
Processing file hrmt.sci
Processing file htrianr.sci
Processing file invr.sci
Processing file lcm.sci
Processing file numer.sci
Processing file pdiv.sci
Processing file pol2des.sci
Processing file pol2str.sci
Processing file polfact.sci
Processing file routh_t.sci
Processing file rowcompr.sci
Processing file sylm.sci
Processing file systmat.sci
Processing file pfactors.sci
Processing file factors.sci
Processing file lcmdiag.sci
Starting Compilation
Running Scilab
generating lib and names
Running Scilab
End of compilation
making test in macros/comm...
Processing file ExecScilab.sci
Processing file ExeclScilab.sci
Starting Compilation
Running Scilab
generating lib and names
Running Scilab
End of compilation
making test in macros/elem...
Processing file acos.sci
Processing file acosm.sci
Processing file acosh.sci
Processing file acoshm.sci
Processing file asin.sci
Processing file asinm.sci
Processing file asinh.sci
Processing file asinhm.sci
Processing file atanh.sci
Processing file atanhm.sci
Processing file cosh.sci
Processing file coshm.sci
Processing file cotg.sci
Processing file coth.sci
Processing file cothm.sci
Processing file log10.sci
Processing file sinh.sci
Processing file sinhm.sci
Processing file tan.sci
Processing file tanm.sci
Processing file tanh.sci
Processing file tanhm.sci
Processing file logm.sci
Processing file atanm.sci
Processing file cosm.sci
Processing file signm.sci
Processing file sinm.sci
Processing file sqrtm.sci
Processing file null.sci
Processing file fix.sci
Processing file smooth.sci
Processing file toeplitz.sci
Processing file pertrans.sci
Processing file modulo.sci
Processing file interpln.sci
Processing file and.sci
Processing file or.sci
Processing file intl.sci
Processing file intc.sci
Processing file integrate.sci
Processing file erf.sci
Processing file erfc.sci
Processing file erfcx.sci
Processing file speye.sci
Processing file spzeros.sci
Processing file sprand.sci
Processing file intsplin.sci
Processing file inttrap.sci
Processing file GLoad.sci
Processing file isinf.sci
Processing file isnan.sci
Processing file median.sci
Processing file mean.sci
Starting Compilation
Running Scilab
generating lib and names
Running Scilab
End of compilation
making test in macros/metanet...
Processing file adj_lists.sci
Processing file add_edge.sci
Processing file add_node.sci
Processing file arc_graph.sci
Processing file arc_number.sci
Processing file articul.sci
Processing file bandwr.sci
Processing file best_match.sci
Processing file chain_struct.sci
Processing file check_graph.sci
Processing file circuit.sci
Processing file con_nodes.sci
Processing file connex.sci
Processing file contract_edge.sci
Processing file convex_hull.sci
Processing file cycle_basis.sci
Processing file delete_arcs.sci
Processing file delete_nodes.sci
Processing file edge_number.sci
Processing file find_path.sci
Processing file gen_net.sci
Processing file girth.sci
Processing file graph_2_mat.sci
Processing file graph_center.sci
Processing file graph_complement.sci
Processing file graph_diameter.sci
Processing file graph_power.sci
Processing file graph_simp.sci
Processing file graph_sum.sci
Processing file graph_union.sci
Processing file hamilton.sci
Processing file knapsack.sci
Processing file nodes_degrees.sci
Processing file is_connex.sci
Processing file line_graph.sci
Processing file load_graph.sci
Processing file make_graph.sci
Processing file mat_2_graph.sci
Processing file max_cap_path.sci
Processing file max_clique.sci
Processing file max_flow.sci
Processing file mesh2d.sci
Processing file metanet.sci
Processing file metanet_sync.sci
Processing file min_lcost_cflow.sci
Processing file min_lcost_flow1.sci
Processing file min_lcost_flow2.sci
Processing file min_qcost_flow.sci
Processing file min_weight_tree.sci
Processing file neighbors.sci
Processing file node_number.sci
Processing file nodes_2_path.sci
Processing file path_2_nodes.sci
Processing file perfect_match.sci
Processing file pipe_network.sci
Processing file plot_graph.sci
Processing file predecessors.sci
Processing file qassign.sci
Processing file salesman.sci
Processing file save_graph.sci
Processing file shortest_path.sci
Processing file show_arcs.sci
Processing file show_graph.sci
Processing file show_nodes.sci
Processing file split_edge.sci
Processing file strong_con_nodes.sci
Processing file strong_connex.sci
Processing file subgraph.sci
Processing file successors.sci
Processing file supernode.sci
Processing file trans_closure.sci
Starting Compilation
Running Scilab
generating lib and names
Running Scilab
End of compilation
making test in macros/optim...
Processing file linpro.sci
Processing file quapro.sci
Processing file karmarkar.sci
Processing file pack.sci
Processing file unpack.sci
Processing file lmitool.sci
Processing file lmisolver.sci
Processing file vec2list.sci
Processing file list2vec.sci
Processing file pencost.sci
Processing file aplat.sci
Processing file fit_dat.sci
Starting Compilation
Running Scilab
generating lib and names
Running Scilab
End of compilation
making test in macros/percent...
Processing file %ce.sci
Processing file %cic.sci
Processing file %cnl.sci
Processing file %col.sci
Processing file %lnc.sci
Processing file %lnl.sci
Processing file %lnm.sci
Processing file %lnp.sci
Processing file %lns.sci
Processing file %loc.sci
Processing file %lol.sci
Processing file %lom.sci
Processing file %lop.sci
Processing file %los.sci
Processing file %lssalss.sci
Processing file %lssap.sci
Processing file %lssar.sci
Processing file %lssas.sci
Processing file %lssclss.sci
Processing file %lsscp.sci
Processing file %lsscr.sci
Processing file %lsscs.sci
Processing file %lsse.sci
Processing file %lssflss.sci
Processing file %lssfp.sci
Processing file %lssfr.sci
Processing file %lssfs.sci
Processing file %lssilss.sci
Processing file %lssip.sci
Processing file %lssir.sci
Processing file %lssis.sci
Processing file %lssllss.sci
Processing file %lsslp.sci
Processing file %lsslr.sci
Processing file %lssls.sci
Processing file %lssmlss.sci
Processing file %lssmp.sci
Processing file %lssmr.sci
Processing file %lssms.sci
Processing file %lssnlss.sci
Processing file %lssnp.sci
Processing file %lssnr.sci
Processing file %lssns.sci
Processing file %lssolss.sci
Processing file %lssop.sci
Processing file %lssor.sci
Processing file %lssos.sci
Processing file %lssrlss.sci
Processing file %lssrp.sci
Processing file %lssrr.sci
Processing file %lssrs.sci
Processing file %lsss.sci
Processing file %lssslss.sci
Processing file %lsssp.sci
Processing file %lsssr.sci
Processing file %lssss.sci
Processing file %lsst.sci
Processing file %lssvlss.sci
Processing file %lssvp.sci
Processing file %lssvr.sci
Processing file %lssvs.sci
Processing file %mnl.sci
Processing file %mol.sci
Processing file %palss.sci
Processing file %par.sci
Processing file %pclss.sci
Processing file %pcr.sci
Processing file %pdp.sci
Processing file %pdr.sci
Processing file %pe.sci
Processing file %pflss.sci
Processing file %pfr.sci
Processing file %pilss.sci
Processing file %pip.sci
Processing file %pir.sci
Processing file %pis.sci
Processing file %pllss.sci
Processing file %plp.sci
Processing file %plr.sci
Processing file %pls.sci
Processing file %pmlss.sci
Processing file %pmr.sci
Processing file %pnl.sci
Processing file %pnlss.sci
Processing file %pnr.sci
Processing file %pol.sci
Processing file %polss.sci
Processing file %por.sci
Processing file %pps.sci
Processing file %pjs.sci
Processing file %pqp.sci
Processing file %pqr.sci
Processing file %pqs.sci
Processing file %prlss.sci
Processing file %prp.sci
Processing file %prr.sci
Processing file %pslss.sci
Processing file %psr.sci
Processing file %pvlss.sci
Processing file %pvp.sci
Processing file %pvr.sci
Processing file %pvs.sci
Processing file %pxr.sci
Processing file %ralss.sci
Processing file %rap.sci
Processing file %rar.sci
Processing file %ras.sci
Processing file %rclss.sci
Processing file %rcp.sci
Processing file %rcr.sci
Processing file %rcs.sci
Processing file %rdp.sci
Processing file %rdr.sci
Processing file %rds.sci
Processing file %re.sci
Processing file %rflss.sci
Processing file %rfp.sci
Processing file %rfr.sci
Processing file %rfs.sci
Processing file %rilss.sci
Processing file %rip.sci
Processing file %rir.sci
Processing file %ris.sci
Processing file %rllss.sci
Processing file %rlp.sci
Processing file %rlr.sci
Processing file %rls.sci
Processing file %rmlss.sci
Processing file %rmp.sci
Processing file %rmr.sci
Processing file %rms.sci
Processing file %rnlss.sci
Processing file %rnp.sci
Processing file %rnr.sci
Processing file %rns.sci
Processing file %rolss.sci
Processing file %rop.sci
Processing file %ror.sci
Processing file %ros.sci
Processing file %rps.sci
Processing file %rjs.sci
Processing file %rqp.sci
Processing file %rqr.sci
Processing file %rqs.sci
Processing file %rrlss.sci
Processing file %rrp.sci
Processing file %rrr.sci
Processing file %rrs.sci
Processing file %rs.sci
Processing file %rslss.sci
Processing file %rsp.sci
Processing file %rsr.sci
Processing file %rss.sci
Processing file %rt.sci
Processing file %rvlss.sci
Processing file %rvp.sci
Processing file %rvr.sci
Processing file %rvs.sci
Processing file %rxp.sci
Processing file %rxr.sci
Processing file %rxs.sci
Processing file %salss.sci
Processing file %sar.sci
Processing file %sclss.sci
Processing file %scr.sci
Processing file %sdp.sci
Processing file %sdr.sci
Processing file %se.sci
Processing file %sflss.sci
Processing file %sfr.sci
Processing file %sic.sci
Processing file %silss.sci
Processing file %sip.sci
Processing file %sir.sci
Processing file %sis.sci
Processing file %sllss.sci
Processing file %slr.sci
Processing file %smlss.sci
Processing file %smr.sci
Processing file %snl.sci
Processing file %snlss.sci
Processing file %snr.sci
Processing file %sol.sci
Processing file %solss.sci
Processing file %sor.sci
Processing file %sqr.sci
Processing file %srlss.sci
Processing file %srp.sci
Processing file %srr.sci
Processing file %sslss.sci
Processing file %ssr.sci
Processing file %svlss.sci
Processing file %svp.sci
Processing file %svr.sci
Processing file %svs.sci
Processing file %sxr.sci
Processing file %bcspb.sci
Processing file %bfspb.sci
Processing file %bgspb.sci
Processing file %bhspb.sci
Processing file %sasp.sci
Processing file %scsp.sci
Processing file %sfsp.sci
Processing file %spas.sci
Processing file %spbcb.sci
Processing file %spbfb.sci
Processing file %spbgb.sci
Processing file %spbgspb.sci
Processing file %spbhb.sci
Processing file %spbhspb.sci
Processing file %spbib.sci
Processing file %spcs.sci
Processing file %spfs.sci
Processing file %spis.sci
Processing file %spss.sci
Processing file %sssp.sci
Processing file %sib.sci
Processing file %spls.sci
Processing file %splsp.sci
Processing file %slsp.sci
Processing file %sprs.sci
Processing file %srsp.sci
Processing file %sprsp.sci
Processing file %cilss.sci
Processing file %cir.sci
Processing file %spksp.sci
Processing file %sksp.sci
Processing file %spks.sci
Processing file %spysp.sci
Processing file %sysp.sci
Processing file %spys.sci
Processing file %spzsp.sci
Processing file %szsp.sci
Processing file %spzs.sci
Processing file %sqp.sci
Processing file %pds.sci
Processing file %prs.sci
Processing file %slp.sci
Processing file %spe.sci
Processing file %sisp.sci
Processing file %spasp.sci
Processing file %spssp.sci
Processing file %sdsp.sci
Processing file %spqs.sci
Processing file %spdsp.sci
Processing file %spqsp.sci
Processing file %spds.sci
Processing file %sqsp.sci
Processing file %choose.sci
Processing file %nochoose.sci
Processing file %sgs.sci
Processing file %shs.sci
Processing file %bgs.sci
Processing file %bhs.sci
Processing file %sgb.sci
Processing file %shb.sci
Processing file %pks.sci
Processing file %skp.sci
Processing file %pkp.sci
Processing file %skr.sci
Processing file %pkr.sci
Processing file %rkp.sci
Processing file %rks.sci
Processing file %rkr.sci
Processing file %pyp.sci
Processing file %pyr.sci
Processing file %pys.sci
Processing file %ryp.sci
Processing file %ryr.sci
Processing file %rys.sci
Processing file %syp.sci
Processing file %syr.sci
Processing file %pzp.sci
Processing file %pzr.sci
Processing file %pzs.sci
Processing file %rzp.sci
Processing file %rzr.sci
Processing file %rzs.sci
Processing file %szp.sci
Processing file %szr.sci
Processing file %s5.sci
Processing file %r_p.sci
Processing file %ar_p.sci
Starting Compilation
Running Scilab
generating lib and names
Running Scilab
End of compilation
making test in macros/robust...
Processing file bstap.sci
Processing file copfac.sci
Processing file dcf.sci
Processing file dtsi.sci
Processing file fstabst.sci
Processing file leqe.sci
Processing file gtild.sci
Processing file hankelsv.sci
Processing file linf.sci
Processing file lqg_ltr.sci
Processing file nehari.sci
Processing file riccati.sci
Processing file smga.sci
Processing file des2ss.sci
Processing file fspec.sci
Processing file cfspec.sci
Processing file fourplan.sci
Processing file augment.sci
Processing file gcare.sci
Processing file gfare.sci
Processing file h_cl.sci
Processing file h_inf.sci
Processing file h_inf_st.sci
Processing file h_norm.sci
Processing file lcf.sci
Processing file macglov.sci
Processing file ccontrg.sci
Processing file entropy.sci
Processing file fspecg.sci
Processing file leqr.sci
Processing file gamitg.sci
Processing file lft.sci
Processing file linfn.sci
Processing file parrot.sci
Processing file ric_desc.sci
Processing file sensi.sci
Processing file tf2des.sci
Processing file h2norm.sci
Processing file rowinout.sci
Processing file colinout.sci
Processing file dhnorm.sci
Starting Compilation
Running Scilab
generating lib and names
Running Scilab
End of compilation
making test in macros/sci2for...
Processing file sci2for.sci
Processing file adderr.sci
Processing file basparam.sci
Processing file cla2for.sci
Processing file cod2for.sci
Processing file exp2for.sci
Processing file f_argn.sci
Processing file f_cos.sci
Processing file f_ent.sci
Processing file f_error.sci
Processing file f_eye.sci
Processing file f_maxi.sci
Processing file f_mini.sci
Processing file f_norm.sci
Processing file f_sin.sci
Processing file f_size.sci
Processing file forparam.sci
Processing file freewrk.sci
Processing file getwrk.sci
Processing file indent.sci
Processing file indentfor.sci
Processing file ins2for.sci
Processing file isnum.sci
Processing file lin2for.sci
Processing file makeargs.sci
Processing file mltopsfor.sci
Processing file modlst.sci
Processing file op2for.sci
Processing file outname.sci
Processing file setparam.sci
Processing file f_abs.sci
Processing file newlab.sci
Processing file f_exp.sci
Processing file f_gener.sci
Processing file f_tan.sci
Processing file typconv.sci
Processing file warning.sci
Processing file get2f.sci
Processing file num2f.sci
Processing file func2f.sci
Processing file str2f.sci
Processing file getlocal.sci
Processing file gencall.sci
Processing file genif.sci
Processing file f_cond.sci
Processing file f_rank.sci
Processing file f_svd.sci
Processing file dclfun.sci
Processing file callfun.sci
Processing file f_log.sci
Processing file f_ones.sci
Processing file f_sqrt.sci
Processing file f_type.sci
Processing file f_max.sci
Processing file f_min.sci
Processing file %a2for.sci
Processing file %cc2for.sci
Processing file %i2for.sci
Processing file %log2for.sci
Processing file %r2for.sci
Processing file %s2for.sci
Processing file %c2for.sci
Processing file %e2for.sci
Processing file %imp2for.sci
Processing file %m2for.sci
Processing file %rc2for.sci
Processing file %t2for.sci
Processing file f_expm.sci
Processing file f_zeros.sci
Starting Compilation
Running Scilab
generating lib and names
Running Scilab
End of compilation
making test in macros/signal...
Processing file %k.sci
Processing file %asn.sci
Processing file %sn.sci
Processing file analpf.sci
Processing file bilt.sci
Processing file buttmag.sci
Processing file casc.sci
Processing file cheb1mag.sci
Processing file cheb2mag.sci
Processing file chepol.sci
Processing file cspect.sci
Processing file czt.sci
Processing file dft.sci
Processing file ell1mag.sci
Processing file eqfir.sci
Processing file cepstrum.sci
Processing file eqiir.sci
Processing file faurre.sci
Processing file ffilt.sci
Processing file findm.sci
Processing file find_freq.sci
Processing file frfit.sci
Processing file frmag.sci
Processing file fsfirlin.sci
Processing file fwiir.sci
Processing file group.sci
Processing file hank.sci
Processing file hilb.sci
Processing file iir.sci
Processing file iirgroup.sci
Processing file iirlp.sci
Processing file iirmod.sci
Processing file intdec.sci
Processing file jmat.sci
Processing file kalm.sci
Processing file lattn.sci
Processing file lev.sci
Processing file levin.sci
Processing file yulewalk.sci
Processing file lindquist.sci
Processing file mese.sci
Processing file mfft.sci
Processing file mrfit.sci
Processing file phc.sci
Processing file pspect.sci
Processing file remezb.sci
Processing file sinc.sci
Processing file sincd.sci
Processing file srfaur.sci
Processing file sskf.sci
Processing file convol.sci
Processing file srkf.sci
Processing file system.sci
Processing file trans.sci
Processing file wfir.sci
Processing file wiener.sci
Processing file wigner.sci
Processing file window.sci
Processing file zpbutt.sci
Processing file zpch1.sci
Processing file zpch2.sci
Processing file zpell.sci
Starting Compilation
Running Scilab
generating lib and names
Running Scilab
End of compilation
making test in macros/tdcs...
Processing file artest.sci
Processing file boucle.sci
Processing file comric.sci
Processing file exemple.sci
Processing file finit.sci
Processing file gaincom.sci
Processing file gainobs.sci
Processing file gpeche.sci
Processing file logr.sci
Processing file lotest.sci
Processing file mineInit.sci
Processing file obscont1.sci
Processing file obsric.sci
Processing file portrait.sci
Processing file portr3d.sci
Processing file recur.sci
Processing file tangent.sci
Processing file tdinit.sci
Processing file test_d.sci
Processing file chaintest.sci
Processing file bifish.sci
Processing file systems.sci
Processing file BInit.sci
Starting Compilation
Running Scilab
generating lib and names
Running Scilab
End of compilation
making test in macros/util...
Processing file sysconv.sci
Processing file readc_.sci
Processing file lin.sci
Processing file halt.sci
Processing file bloc2exp.sci
Processing file pol2tex.sci
Processing file texprint.sci
Processing file bloc2ss.sci
Processing file cmb_lin.sci
Processing file eval.sci
Processing file evstr.sci
Processing file solve.sci
Processing file trianfml.sci
Processing file trisolve.sci
Processing file sci2map.sci
Processing file logspace.sci
Processing file linspace.sci
Processing file ssprint.sci
Processing file ssrand.sci
Processing file sysdiag.sci
Processing file syslin.sci
Processing file syssize.sci
Processing file trfmod.sci
Processing file manedit.sci
Processing file x_matrix.sci
Processing file typeof.sci
Processing file isdef.sci
Processing file zeros.sci
Processing file edit.sci
Processing file getvalue.sci
Processing file usermenu.sci
Processing file macrovar.sci
Processing file input.sci
Processing file sci2exp.sci
Processing file demos.sci
Processing file whereami.sci
Processing file printf.sci
Processing file fprintf.sci
Processing file sprintf.sci
Processing file scanf.sci
Processing file fscanf.sci
Processing file sscanf.sci
Processing file xdialog.sci
Processing file unix_g.sci
Processing file unix_s.sci
Processing file unix_x.sci
Processing file unix_w.sci
Processing file x_choices.sci
Processing file odeoptions.sci
Processing file whos.sci
Processing file newest.sci
Processing file excel2sci.sci
Processing file dec2hex.sci
Processing file hex2dec.sci
Processing file getd.sci
Processing file %b_diag.sci
Processing file %b_tril.sci
Processing file %b_triu.sci
Processing file %c_diag.sci
Processing file %c_eye.sci
Processing file %c_ones.sci
Processing file %c_rand.sci
Processing file %c_tril.sci
Processing file %c_triu.sci
Processing file %lss_eye.sci
Processing file %lss_inv.sci
Processing file %lss_ones.sci
Processing file %lss_rand.sci
Processing file %lss_size.sci
Processing file %p_det.sci
Processing file %p_inv.sci
Processing file %p_prod.sci
Processing file %p_sum.sci
Processing file %r_clean.sci
Processing file %r_det.sci
Processing file %r_diag.sci
Processing file %r_eye.sci
Processing file %r_inv.sci
Processing file %r_ones.sci
Processing file %r_rand.sci
Processing file %r_size.sci
Processing file %r_tril.sci
Processing file %r_triu.sci
Processing file %s_pow.sci
Processing file %s_sort.sci
Processing file %s_simp.sci
Processing file %p_simp.sci
Processing file %r_simp.sci
Processing file %sp_ceil.sci
Processing file %sp_cos.sci
Processing file %sp_diag.sci
Processing file %sp_exp.sci
Processing file %sp_floor.sci
Processing file %sp_imag.sci
Processing file %sp_int.sci
Processing file %sp_inv.sci
Processing file %sp_real.sci
Processing file %sp_round.sci
Processing file %sp_sin.sci
Processing file %sp_sort.sci
Processing file %sp_sqrt.sci
Processing file %sp_sum.sci
Processing file %sp_tril.sci
Processing file %sp_triu.sci
Processing file %spb_diag.sci
Processing file %spb_tril.sci
Processing file %spb_triu.sci
Starting Compilation
Running Scilab
generating lib and names
Running Scilab
End of compilation
making test in macros/xdess...
Processing file errbar.sci
Processing file fchamp.sci
Processing file fcontour.sci
Processing file fplot2d.sci
Processing file fplot3d.sci
Processing file fgrayplot.sci
Processing file fplot3d1.sci
Processing file locate.sci
Processing file xbasc.sci
Processing file xbasimp.sci
Processing file xbasr.sci
Processing file xclip.sci
Processing file xstringb.sci
Processing file histplot.sci
Processing file plot.sci
Processing file eval3d.sci
Processing file gr_menu.sci
Processing file hist3d.sci
Processing file scaling.sci
Processing file isoview.sci
Processing file milk_drop.sci
Processing file xrpoly.sci
Processing file rotate.sci
Processing file secto3d.sci
Processing file square.sci
Processing file titlepage.sci
Processing file nyquist.sci
Processing file m_circle.sci
Processing file bode.sci
Processing file chart.sci
Processing file black.sci
Processing file plzr.sci
Processing file gainplot.sci
Processing file evans.sci
Processing file zgrid.sci
Processing file graduate.sci
Processing file fac3d.sci
Processing file fac3d1.sci
Processing file eval3dp.sci
Processing file plotframe.sci
Processing file xsetm.sci
Processing file edit_curv.sci
Processing file drawmbar.sci
Processing file getmenu.sci
Processing file genfac3d.sci
Processing file Sgrayplot.sci
Processing file Sfgrayplot.sci
Processing file fcontour2d.sci
Processing file addcolor.sci
Processing file replot.sci
Processing file sgrid.sci
Processing file hotcolormap.sci
Processing file graycolormap.sci
Starting Compilation
Running Scilab
generating lib and names
Running Scilab
End of compilation
making test in macros/scicos...
Processing file clickin.sci
Processing file draw.sci
Processing file drawblock.sci
Processing file drawlink.sci
Processing file drawobj.sci
Processing file drawobjs.sci
Processing file drawpal.sci
Processing file getblock.sci
Processing file getinputs.sci
Processing file getlink.sci
Processing file getobj.sci
Processing file getorigin.sci
Processing file getoutputs.sci
Processing file gridpoint.sci
Processing file scicos.sci
Processing file standard_draw.sci
Processing file standard_inputs.sci
Processing file standard_origin.sci
Processing file standard_outputs.sci
Processing file systshow.sci
Processing file analyse.sci
Processing file default_color.sci
Processing file do_move.sci
Processing file do_compile.sci
Processing file prt_align.sci
Processing file standard_block.sci
Processing file mark_prt.sci
Processing file get_connected.sci
Processing file c_pass1.sci
Processing file c_pass2.sci
Processing file modipar.sci
Processing file do_setup.sci
Processing file standard_define.sci
Processing file stripblanks.sci
Processing file get_tree_elt.sci
Processing file change_tree_elt.sci
Processing file choosefile.sci
Processing file lstfiles.sci
Processing file projaff.sci
Processing file do_delete.sci
Processing file check_io.sci
Processing file do_tild.sci
Processing file do_copy.sci
Processing file save_super.sci
Processing file genfunc.sci
Processing file genfunc1.sci
Processing file drawtitle.sci
Processing file getparpath.sci
Processing file save_csuper.sci
Processing file do_help.sci
Processing file do_run.sci
Processing file do_replace.sci
Processing file getcolor.sci
Processing file do_purge.sci
Processing file do_view.sci
Processing file do_fsave.sci
Processing file do_window.sci
Processing file mark_newpars.sci
Processing file getportsiz.sci
Processing file do_block.sci
Processing file do_load.sci
Processing file do_SaveAs.sci
Processing file do_resize.sci
Processing file do_version.sci
Processing file splitfilepath.sci
Processing file check_mac.sci
Processing file countblocks.sci
Processing file shiftcors.sci
Processing file ctree.sci
Processing file genmac.sci
Processing file mkvect.sci
Processing file do_newblk.sci
Processing file setvalue.sci
Processing file do_label.sci
Processing file cos2txt.sci
Processing file do_color.sci
Processing file do_save.sci
Processing file c_pass3.sci
Processing file hilite_obj.sci
Processing file unhilite_obj.sci
Processing file do_eval.sci
Processing file do_exit.sci
Processing file adjust.sci
Processing file lnkptrcomp.sci
Processing file init_agenda.sci
Processing file do_terminate.sci
Processing file do_update.sci
Processing file bad_connection.sci
Processing file delete_unconnected.sci
Processing file do_delete1.sci
Processing file get_subobj_path.sci
Processing file get_new_window.sci
Processing file add_palette.sci
Processing file do_palettes.sci
Processing file do_edit_pal.sci
Processing file do_addnew.sci
Processing file update_scicos_pal.sci
Processing file save_scs_gc.sci
Processing file restore_scs_gc.sci
Processing file cos2cosf.sci
Processing file changeports.sci
Processing file update_redraw_obj.sci
Processing file do_copy_region.sci
Processing file do_delete_region.sci
Processing file do_context.sci
Processing file scs_show.sci
Processing file generic_block.sci
Processing file do_rename.sci
Processing file message.sci
Processing file dialog.sci
Processing file fortran_block.sci
Processing file do_forcomlink.sci
Processing file do_zoomin.sci
Processing file do_zoomout.sci
Starting Compilation
Running Scilab
generating lib and names
Running Scilab
End of compilation
making test in macros/scicos_blocks...
Processing file SPLIT_f.sci
Processing file GAIN_f.sci
Processing file IN_f.sci
Processing file CLKIN_f.sci
Processing file OUT_f.sci
Processing file CLKOUT_f.sci
Processing file CLKOUTV_f.sci
Processing file CLKINV_f.sci
Processing file CLKSOMV_f.sci
Processing file GAINBLK_f.sci
Processing file QUANT_f.sci
Processing file CLKSPLIT_f.sci
Processing file CLKSOM_f.sci
Processing file EVTDLY_f.sci
Processing file SAT_f.sci
Processing file SOM_f.sci
Processing file SUPER_f.sci
Processing file SCOPE_f.sci
Processing file CLSS_f.sci
Processing file DLSS_f.sci
Processing file CLR_f.sci
Processing file DLR_f.sci
Processing file ZCROSS_f.sci
Processing file m_sin.sci
Processing file TRASH_f.sci
Processing file CONST_f.sci
Processing file DELAY_f.sci
Processing file SELECT_f.sci
Processing file PROD_f.sci
Processing file TEXT_f.sci
Processing file CLOCK_f.sci
Processing file EVTGEN_f.sci
Processing file IFTHEL_f.sci
Processing file func_block.sci
Processing file scifunc_block.sci
Processing file EXPBLK_f.sci
Processing file WFILE_f.sci
Processing file SINBLK_f.sci
Processing file COSBLK_f.sci
Processing file TANBLK_f.sci
Processing file INVBLK_f.sci
Processing file LOGBLK_f.sci
Processing file POWBLK_f.sci
Processing file HALT_f.sci
Processing file GENSIN_f.sci
Processing file RAND_f.sci
Processing file ABSBLK_f.sci
Processing file LOOKUP_f.sci
Processing file TIME_f.sci
Processing file NEGTOPOS_f.sci
Processing file POSTONEG_f.sci
Processing file GENERAL_f.sci
Processing file REGISTER_f.sci
Processing file CLINDUMMY_f.sci
Processing file GENSQR_f.sci
Processing file MFCLCK_f.sci
Processing file SAWTOOTH_f.sci
Processing file MCLOCK_f.sci
Processing file TCLSS_f.sci
Processing file SCOPXY_f.sci
Processing file EVENTSCOPE_f.sci
Processing file INTEGRAL_f.sci
Processing file RFILE_f.sci
Processing file ANIMXY_f.sci
Processing file CURV_f.sci
Processing file MIN_f.sci
Processing file MAX_f.sci
Processing file DLRADAPT_f.sci
Processing file ANDLOG_f.sci
Processing file MUX_f.sci
Processing file DEMUX_f.sci
Processing file DELAYV_f.sci
Processing file SAMPLEHOLD_f.sci
Processing file ANDBLK.sci
Processing file DOLLAR_f.sci
Processing file AFFICH_f.sci
Processing file MSCOPE_f.sci
Processing file NRMSOM_f.sci
Processing file ISELECT_f.sci
Processing file ESELECT_f.sci
Processing file BIGSOM_f.sci
Processing file INTRPLBLK_f.sci
Processing file INTRP2BLK_f.sci
Starting Compilation
Running Scilab
generating lib and names
Running Scilab
End of compilation
making test in macros/sound...
Processing file analyze.sci
Processing file mapsound.sci
Processing file soundsec.sci
Starting Compilation
Running Scilab
generating lib and names
Running Scilab
End of compilation
making test in macros/fraclab...
Processing file AtanH.sci
Processing file GeneWei.sci
Processing file MFAG_continuous.sci
Processing file MFAG_discrete.sci
Processing file MFAG_epsilon_eta.sci
Processing file MFAG_eta.sci
Processing file MFAG_net.sci
Processing file MakeCQF.sci
Processing file MakeQMF.sci
Processing file WT2DNbScales.sci
Processing file WT2DSize.sci
Processing file WT2DStruct.sci
Processing file WT2DVisu.sci
Processing file WT2Dext.sci
Processing file WTMultScales.sci
Processing file WTMultires.sci
Processing file WTNbScales.sci
Processing file WTOrigSize.sci
Processing file WTPump.sci
Processing file WTShrink.sci
Processing file WTStruct.sci
Processing file all.sci
Processing file contwt.sci
Processing file contwtmir.sci
Processing file contwtspec.sci
Processing file cwtspec.sci
Processing file denois.sci
Processing file diff.sci
Processing file dilate.sci
Processing file dwtspec.sci
Processing file fbmlevinson.sci
Processing file fft1d.sci
Processing file fftshift.sci
Processing file findWTLM.sci
Processing file fliplr.sci
Processing file flipud.sci
Processing file flt.sci
Processing file fmt.sci
Processing file gauss.sci
Processing file hilbert.sci
Processing file hot.sci
Processing file icontwt.sci
Processing file ifmt.sci
Processing file integ.sci
Processing file isempty.sci
Processing file isreal.sci
Processing file lambdak.sci
Processing file log2.sci
Processing file mbmlevinson.sci
Processing file mean.sci
Processing file mexhat.sci
Processing file morlet.sci
Processing file nextpowQ.sci
Processing file oscillsing.sci
Processing file pseudoAW.sci
Processing file rem.sci
Processing file sortup.sci
Processing file viewmat.sci
Starting Compilation
Running Scilab
generating lib and names
Running Scilab
End of compilation
