.TH  1 "April 1993" "Scilab Group" "Scilab Function"
.so ../sci.an
.SH NAME
equal (=) - affectation, comparison equal sign
.SH DESCRIPTION
Equal sign is used to denote a value affectation to a variable.
.LP
== denote equality comparison between two expressions and returns a boolean
matrix.
.SH EXAMPLES
.nf
a=sin(3.2)
[u,s]=schur(rand(3,3))
[1:10]==4
1~=2
.fi
.SH SEE ALSO
less, boolean



