.TH funptr G "April 1993" "Scilab Group" "Scilab Function"
.so ../sci.an
.SH NAME
funptr - coding of  primitives ( wizard stuff )
.SH DESCRIPTION
Utility function (for experts only) 
.Vb funptr('name') 
returns 
.Vb 100*fun + fin 
where \fV(fun,fin)\fR is the internal coding of the primitive \fV'name'\fR .
\fVfun\fR is the interface number and \fVfin\fR the routine number
.SH SEE ALSO
clearfun, newfun

