.TH less 1 "April 1993" "Scilab Group" "Scilab Function"
.so ../sci.an
.SH NAME
less (<) - lower than comparison
.SH DESCRIPTION
logical comparison symbol
.TP
<>
means "different" (same as \fV~=\fR)
.TP
<
means "lower than"
.TP
>
means "larger than"
.TP
<=
means lower than or equal to.
.TP
>=
means larger than or equal to
.SH SEE ALSO
if 
