.TH pwd 1 "April 1998" "Scilab Group" "Scilab command"
.so ../sci.an
.SH NAME
pwd - print Scilab current directory
getcwd - get Scilab current directory
.SH CALLING SEQUENCE
.nf
pwd
x=pwd()
x=getwcd()
.fi
.SH DESCRIPTION
\fVpwd\fR returns in \fVans\fR the Scilab current directory.
\fVx=pwd()\fR or fVx=getcwd()\fR returns in \fVx\fR the Scilab current
directory.

.SH EXAMPLE
.nf
pwd
x=pwd()
.fi
.SH SEE ALSO
chdir, unix

