.TH narsimul 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
narsimul - armax simulation ( using rtitr) 
.SH DESCRIPTION
[z]=narsimul(a,b,d,sig,u,[up,yp,ep])

[z]=narsimul(ar,u,[up,yp,ep])

ARMAX simulation. Same as arsimul but the method is different 
the simulation is made with rtitr 
.SH AUTHOR 
J-Ph. Chancelier ENPC Cergrene


