.TH erfc 3 "December 1994" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
erfc -  The complementary error function.
.SH SYNTAX
 y = erfc(x)
.SH PARAMETERS
.TP
x
: real vector
.TP
y
: real vector (of same size)
.SH DESCRIPTION
 \fVerfc\fR computes the complementary error function:
.nf
                      /inf
     y = 2/sqrt(pi) *|  exp(-t^2) dt
                     /x

     y= 1 - erf(x)
.fi
.SH SEE ALSO
erf erfcx calerf




