.TH trianfml 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
trianfml - symbolic triangularization
.SH CALLING SEQUENCE
.nf
[f [,sexp]]=trianfml(f [,sexp])
.fi
.SH DESCRIPTION
Triangularization of the symbolic matrix \fVf\fR ; triangularization 
is performed by elementary row operations;
\fVsexp\fR is a set of common expressions stored by the algorithm.

