.TH convstr 1 "April 1993" "Scilab Group" "Scilab Function"
.so ../sci.an
.SH NAME
convstr - case conversion
.SH CALLING SEQUENCE
.nf
[y]=convstr(str-matrix, ["flag"]) 
.fi
.SH PARAMETERS
.TP 10
str-matrix, y
: matrices of strings
.TP 10
"flag"
: string (\fV"u"\fR for upper or \fV"l"\fR for lower (default value))
.SH DESCRIPTION
converts the matrix of strings \fVstr-matrix\fR
into lower case (for \fV"l"\fR ;default value) or
upper case (for \fV"u"\fR).
.SH EXAMPLE
.nf
A=['this','is';'my','matrix'];
convstr(A,'u')
.fi


