.TH driver 2 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
driver - select a driver for plotting
.SH CALLING SEQUENCE
.nf
driver(driver_name)
.fi
.SH PARAMETERS 
.TP 15
driver_name 
: string (driver to be selected).
.SH DESCRIPTION
This function is used to select a graphic driver.
Most of the time, a user can ignore this function and change its driver
by calling high level functions such as \fVxbasc\fR or \fVxbasimp\fR.
The selected driver can be one of the following :
.TP 10
"X11"
: an X Window driver.
.TP
"IX11"
: an other X Window driver which can be used under xscilab. 
.TP
"Pos" 
: a Postscript driver.
.TP
"Rec" 
: an X Window driver (IX11) which also records all the graphic commands.
.TP
"Fig" 
: an XFig driver ( not fully released )
.SH SEE ALSO
xtape,xbasc,xbasimp
.SH AUTHOR
J.Ph.C.




