.TH xbasr 2 "April 1993" "Scilab Group" "Scilab Function" 
.so man1/sci.an
.SH NAME
xbasr - redraw a graphic window
.SH CALLING SEQUENCE
.nf
xbasr(win_num)
.fi
.SH DESCRIPTION
This function is used to redraw the content of the graphic 
window of id \fVwin_num\fR. It works only with the driver \fV"Rec"\fR.
.SH SEE ALSO
xtape, driver
.SH AUTHOR
J.Ph.C.



