.TH delmenu 3 "December 1995" "Scilab Group" "Scilab Function"
.so ../sci.an
.SH NAME
delmenu - interactive button or menu deletion
.SH CALLING SEQUENCE
.nf
delmenu(button) 
delmenu(gwin,button)
.fi
.SH PARAMETERS
.TP
button
: a character string. The button name. On Windows operating
systems (not X_window), an @ should be placed before the character
in the name used for keyboard shortcut; this character
is underlined on the GUI. 
.TP
gwin
: integer. The number of graphic window where the button is required
to be installed
.SH DESCRIPTION
The function allows the user to delete  buttons or menus create by
\fVaddmenu\fR in the main or graphics windows command panels. 
Predefined buttons on Scilab graphic windows can also be deleted.

If possible, it is better to delete first the latest created button
for a given window to avoid gaps in  command panels.
.SH EXAMPLE
.nf
addmenu('foo')
delmenu('foo')
.fi
.SH SEE ALSO
setmenu, unsetmenu, addmenu
