.TH names 1 "April 1993" "Scilab Group" "Scilab Syntax"
.so ../sci.an
.SH NAME
names - scilab names syntax
.SH DESCRIPTION
Names of variables and functions must begin with a letter or one of
the following special characters  '\fV%\fR', '\fV_\fR', '\fV#\fR', '\fV!\fR', '\fV$\fR', '\fV?\fR'.


Next characters may be letters or digits or any special character in '\fV_\fR', '\fV#\fR', '\fV!\fR', '\fV$\fR', '\fV?\fR'


Names may be as long as you want but only the first 24  characters are
taken into account. Upper and lower case letters are different.

.SH EXAMPLES
.nf
//Valid names
%eps
A1=123
#Color=8
My_Special_Color_Table=rand(10,3)
//Non valid names
//1A , b%, .C
.fi
