.TH ldivf 1 "April 1993" "Scilab Group" "Scilab Function"
.so ../sci.an
.SH NAME
rdivf - right symbolic division
.SH CALLING SEQUENCE
.nf
["r"]=ldivf("d","c") 
.fi
.SH PARAMETERS
.TP 15
"d","c","r"
: strings
.SH DESCRIPTION
returns the string \fV"c/d"\fR
Trivial simplifications such as \fV"c/1" = "c"\fR are performed.
.SH EXAMPLE
.nf
ldivf('c','d')
ldivf('1','2')
ldivf('a','0')
.fi
.SH SEE ALSO
ldivf
