.TH subf 3 "April 1993" "Scilab Group" "Scilab Function"
.so ../sci.an
.SH NAME  
subf -  symbolic subtraction
.SH CALLING SEQUENCE
.nf
["c"]=subf("a","b")
.fi
.SH PARAMETERS
.TP 10
"a","b","c" 
: strings
.SH DESCRIPTION
returns the character string \fVc\fR=\fV"a-b"\fR
Trivial simplifications such as \fVsubf("0","a")\fR or
\fVsubf("1","2")\fR are performed.
.SH EXAMPLE
.nf
subf('0','a')
subf('2','1')
subf('a','0')
.fi
.SH SEE ALSO
mulf, ldivf, rdivf, eval, evstr


