.TH ilib_gen_gateway 1 "May 2000" "Scilab Group" "Scilab Function"
.so ../sci.an
.SH NAME
ilib_gen_gateway  - utility for ilib_build, generates a gateway file.
.SH CALLING SEQUENCE
.nf
ilib_gen_gateway(name,table)
.fi
.SH PARAMETERS
.TP 10
name
: a character string, the generic name of the library without path and
extension.
.TP 10
table 
: 2 column string matrix giving the table of pairs 'scilab-name' 'interface name'
.SH DESCRIPTION
Utility function used by \fVilib_build\fR
This function generates a gateway file used by \fVaddinter\fR.
.SH SEE ALSO
addinter, link, ilib_build, ilib_compile, ilib_gen_Make,
ilib_gen_loader, ilib_for_link
