.TH ilib_compile 1 "May 2000" "Scilab Group" "Scilab Function"
.so ../sci.an
.SH NAME
ilib_compile - ilib_build utility: executes the makefile produced by ilib_gen_Make
.SH CALLING SEQUENCE
.nf
libn=ilib_compile(lib_name,makename)
.fi
.SH PARAMETERS
.TP 10
lib_name
: : a character string, the generic name of the library without path and
extension.
.TP 10
makename
: character string. The path of the Makefile file without extension.
.TP 10
libn
: character string. The path of the really generated shared library file.
.SH DESCRIPTION
Utility function used by \fVilib_build\fR
.LP 
This executes the  makefile produced by \fVilib_gen_Make\fR, compiles
the C and fortran files and generates the shared library. 
.LP
Shared libraries can then be used with the \fVlink\fR and
\fVaddinter\fR scilab function for incremental linking.
.SH SEE ALSO
addinter, link, ilib_build, ilib_gen_Make, ilib_gen_gateway,
ilib_gen_loader, ilib_for_link



