.TH unix_w 1 "April 1993" "Scilab Group" "Scilab Function"
.so ../sci.an
.SH NAME
unix_w - shell (sh) command execution, output redirected to scilab window
.SH CALLING SEQUENCE
.nf
rep=unix_w(cmd)
.fi
.SH PARAMETERS
.TP 10
cmd 
: a character string
.TP
rep
: a column vector of character strings
.SH DESCRIPTION
Sends a string \fVcmd\fR to Unix for execution by the sh shell. The standard 
output is redirected to scilab window.
Unix execution errors are trapped; *NOTE* that only the last shell command
error is reported when a list of command separated by ";" is sent: this is
not recommended.
.SH EXAMPLE
.nf
if MSDOS then unix_w("dir "+WSCI+"\demos");
else unix_w("ls $SCI/demos"); end
.fi
.SH SEE ALSO
edit, manedit, unix_g, unix_s, unix_x, unix
