.TH "gcf" 2 " 04 June 1998" "Fractales Group" "Scilab Function"
.so ../sci.an
.SH NAME
gcf - gets the current active tksci figure
.SH CALLING SEQUENCE
h=gcf()
.SH  PARAMETERS
.TP
o
h : handle of the current figure.
.SH DESCRIPTION
The current figure is the last created (and still existent) figure.
.SH EXAMPLE
.nf
figure(5);
figure();
figure();
gcf()
// returns 2
close(gcf());
// close figure 2
gcf()
// returns 1
close(1);
gcf()
// returns 5
close(5);
.fi 

.SH SEE ALSO
figure, close
.SH AUTHOR
Bertrand Guiheneuf
