.TH CLKSOM_f 5 "Janvier 1996" "Scilab Group" "Scicos Block"
.so man1/sci.an
.SH NAME
CLKSOM - Scicos event addition block
.SH DESCRIPTION
This block is a clock sum with up to three inputs. The output reproduces
the events on all the input ports. Strictly speaking, CLKSOM is not a
Scicos block because it is discarded at the compilation phase. The
inputs and output of CLKSOM are synchronized (this is impossible for
other basic blocks in Scicos). 









