.TH EVENTSCOPE_f 5 "Janvier 1996" "Scilab Group" "Scicos Block"
.so man1/sci.an
.SH NAME
EVENTFSCOPE - Scicos visualization block
.SH DESCRIPTION
This block allows the visualization of event signals
on its event input port(s).
.SH DIALOG PARAMETERS
.TP 20
Block label
: A string defining the block label. This label is placed under
the block. 
.TP
Number of inputs
: an integer, the number of event input ports.
.TP
Curve colors
: a vector of integers. The i-th element is the color number (<0)
or dash type (>0) used to draw the evolution of the i-th 
input port signal. See \fVplot2d\fR for color (dash type) definitions.
.TP
Output window number
: The number of graphic window used for the display. It is often good
to use high values to avoid conflict with palettes and Super Block
windows. If you have more than one scope, make sure they don't have
the same window numbers (unless superposition of the curves is desired).
.TP
Refresh period
: Maximum value on the X-axis (time). The plot is redrawn when time
reaches a multiple of this value.
.SH SEE ALSO
SCOPXY_f SCOPE_f ANIMXY_f




