.TH EVTDLY_f 5 "Janvier 1996" "Scilab Group" "Scicos Block"
.so man1/sci.an
.SH NAME
EVTDLY - Scicos event delay block
.SH DESCRIPTION
One event is generated dt after an event enters the unique input
event port. The output can be initially fired or not.
.SH DIALOG PARAMETERS
.TP 15
Block label
: string. The block label is placed under the block.
.TP
Delay
: scalar. dt.
.TP
Auto-exec
: 0 or 1. 1 if initially fired.
.SH SEE ALSO
CLOCK_f







