.TH MCLOCK_f 5 "Janvier 1996" "Scilab Group" "Scicos Block"
.so man1/sci.an
.SH NAME
MCLOCK - Scicos 2 frequency event clock
.SH DESCRIPTION
This block is a Super Block constructed by feeding back the outputs
of an MFCLCK block into its input event port. The two
outputs of this block generate regular train of events, the frequency
of the first input being equal to that of the second output diveided
by an integer n. The two outputs are synchronized (this is impossible
for standard blocks; this is a Super Block).
.SH DIALOG PARAMETERS
.TP 15
Block label
: This has no effect on this Super Block
.TP
Basic period
: scalar. equals 1/f, f being the highest frequency.
.TP
n 
: an intger >1. the frequency of the first output event is f/n.
.SH SEE ALSO
MFCLCK_f CLOCK_f







