.TH SUPER_f 5 "Janvier 1996" "Scilab Group" "Scicos Block"
.so man1/sci.an
.SH NAME
SUPER - Scicos Super block
.SH DESCRIPTION
This block opens up a new Scicos window for editing a new block
diagram. This diagram describes the internal functions of the
super block. The number of inputs and outputs are adjusted
automatically based on the number of inputs and outputs blocks in the
diagram.








