.TH code2str 1 "May 1994" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
code2str - returns character string associated with scilab integer codes.
.SH SYNOPSIS
.nf
str=code2str(c)
.fi
.SH PARAMETERS
.TP 
str
: a character string
.TP
c
: vector of character integer codes
.SH DESCRIPTION
Returns character string associated with scilab integer codes.str is
such that  c(i) is the scilab integer code of part(str,i))
.SH EXAMPLE
code2str([-28 12 18 21 10 11])
.SH SEE ALSO
str2code
