.TH getenv G "April 1994" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
getenv - get the value of an environnement variable
.SH CALLING SEQUENCE
.nf
env=getenv(str)
.fi
.SH PARAMETERS
.TP
str
: character string specifying environnement variable name
.TP
env
: character string which contain the environnement variable value
.SH DESCRIPTION
Return the value of an environnement variable 
.SH Example
getenv('SCI')

