.TH print 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
print - prints variables in a file 
.SH CALLING SEQUENCE
.nf
print('file-name',x1,[x2,...xn]) 
.fi
.SH DESCRIPTION
prints \fVxi\fR on file \fV'file-name'\fR
with the current format.
.LP
\fVprint(%io(2),...)\fR prints on Scilab's window.
.SH SEE ALSO
write, read

