.TH xfrect 2 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME 
xfrect - fill a rectangle 
.SH CALLING SEQUENCE
.nf
[]=xfrect(x,y,w,h)
.fi
.SH PARAMETERS
.TP 10
x,y,w,h
: real scalars (rectangle def)
.SH DESCRIPTION
fills  a rectangle \fV[x,y,w,h]\fR (upper-left point, width, height) using current
scale and pattern
.SH AUTHOR
J.Ph.C.


