.TH spec G "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an 
.SH NAME
spec - eigenvalues
.SH CALLING SEQUENCE
.nf
evals=spec(A)
.fi
.SH PARAMETERS
.TP
A 
: real or complex square matrix
.TP
evals
: real or complex vector
.SH DESCRIPTION
.Vb evals=spec(A)
returns in  vector \fVevals\fR the eigenvalues of \fVA\fR.
.LP
Eigenvectors are obtained by \fVbdiag\fR.
.SH SEE ALSO
poly, det, gspec, schur, bdiag, colcomp.

