.TH boucle 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
boucle - phase portrait of a dynamical system with observer
.SH CALLING SEQUENCE
.nf
[]=boucle(fch,[abruit,xdim,npts,farrow])
.fi
.SH DESCRIPTION
Phase portrait of dynamical systems. 
.SH PARAMETERS
.TP
fch
: is supposed to be an observed-controlled system with 
noisy output of state dimension 4 ( [x;xchap] is of dimension 4).
fch can be created with the macro obs_cont or can be one of the two following string
which gives precomputed examples
.RS
.TP 10
"bcomp"
: for a non-linear competition model 
.TP
"lcomp"
: for a linear example
.RE
.TP
abruit
: give the noise variance 
.TP
xdim,npts,farrow
: See portrait 
.SH SEE ALSO
portrait, ode,obs_cont

