SHELL = /bin/sh

SCIDIR=../..
include ../../Makefile.incl

.SUFFIXES: .sci .bin $(SUFFIXES)

NAME = scicoslib
NAM = scicos



MACROS=clickin.sci draw.sci drawblock.sci drawlink.sci drawobj.sci drawobjs.sci \
	drawpal.sci getblock.sci getinputs.sci getlink.sci getobj.sci \
	getorigin.sci getoutputs.sci gridpoint.sci scicos.sci \
	standard_draw.sci standard_inputs.sci standard_origin.sci \
	standard_outputs.sci systshow.sci \
	analyse.sci default_color.sci do_move.sci do_compile.sci \
	prt_align.sci standard_block.sci mark_prt.sci get_connected.sci \
	c_pass1.sci c_pass2.sci modipar.sci do_setup.sci \
	standard_define.sci stripblanks.sci get_tree_elt.sci \
	change_tree_elt.sci choosefile.sci lstfiles.sci \
	projaff.sci do_delete.sci check_io.sci do_tild.sci do_copy.sci \
	save_super.sci genfunc.sci genfunc1.sci drawtitle.sci getparpath.sci \
	save_csuper.sci do_help.sci do_run.sci do_replace.sci getcolor.sci \
	do_purge.sci do_view.sci do_fsave.sci do_window.sci mark_newpars.sci \
	getportsiz.sci do_block.sci do_load.sci do_SaveAs.sci do_resize.sci \
	do_version.sci splitfilepath.sci check_mac.sci countblocks.sci \
	shiftcors.sci  ctree.sci genmac.sci mkvect.sci \
	do_newblk.sci setvalue.sci do_label.sci cos2txt.sci \
	do_color.sci do_save.sci c_pass3.sci hilite_obj.sci \
	unhilite_obj.sci do_eval.sci do_exit.sci adjust.sci lnkptrcomp.sci\
	init_agenda.sci do_terminate.sci do_update.sci bad_connection.sci\
	delete_unconnected.sci do_delete1.sci get_subobj_path.sci \
	get_new_window.sci add_palette.sci do_palettes.sci do_edit_pal.sci\
	do_addnew.sci update_scicos_pal.sci save_scs_gc.sci restore_scs_gc.sci\
	cos2cosf.sci changeports.sci update_redraw_obj.sci do_copy_region.sci\
	do_delete_region.sci do_context.sci scs_show.sci generic_block.sci \
	do_rename.sci message.sci dialog.sci 



include ../Make.lib
