.TH / 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
/ - right division 
.SH DESCRIPTION
Right division.  \fVx=A / b\fR is the solution of \fVx*A=b\fR .
.LP
\fVb/a = (a' \\ b')'\fR .
.LP
\fVa ./  b\fR is the matrix with entries \fVa(i,j)/ b(i,j)\fR.
If \fVb\fR is scalar (1x1 matrix) this operation is the same
as \fV a./b*ones(a)\fR. (Same convention if \fVa\fR is a scalar).
.LP
Backslash stands for left division.
.LP
\fV//\fR comments a line i.e lines which begin by \fV//\fR are
ignored by the interpreter.
.SH SEE ALSO
inv, percent, backslash
