.TH what 1 "April 1993" "Scilab Group" "Scilab Function"
.so man1/sci.an
.SH NAME
whereis - name of library containing a function
.SH CALLING SEQUENCE
.nf
[librname]=whereis(macro-name)
.fi
.SH DESCRIPTION
returns as a character string
the name of the library containing the function \fVmacro-name\fR. 
The path of the library is returned by typing \fV"librname"\fR.
.SH SEE ALSO
lib
