.TH lin2mu 1 "April 1993" "Scilab Group" "Scilab Function"
.so ../sci.an
.SH NAME
lin2mu - linear signal to mu-law encoding
.SH CALLING SEQUENCE
.nf
mu=lin2mu(y)
.fi
.SH PARAMETERS
.TP
y
: real vector
.TP
mu
: real vector
.SH DESCRIPTION
Utility fct: converts linear signal to mu-law encoding.
\fVmu = lin2mu(y)\fR converts linear audio signal amplitudes
in the range  -1 <= y <= 1 to mu-law in the range 0 <= mu <= 255.
.SH SEE ALSO
mu2lin




